-- CoinSparkLine Phase 8 private account data.
-- Run in the Supabase SQL Editor after creating the project.
create table if not exists public.watchlist_items(user_id uuid references auth.users(id) on delete cascade not null,coin_id text not null,created_at timestamptz default now(),primary key(user_id,coin_id));
create table if not exists public.portfolio_items(id bigint generated by default as identity primary key,user_id uuid references auth.users(id) on delete cascade not null,coin_id text not null,symbol text not null,quantity numeric not null check(quantity>=0),average_cost_usd numeric check(average_cost_usd>=0),created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.alert_rules(id bigint generated by default as identity primary key,user_id uuid references auth.users(id) on delete cascade not null,coin_id text not null,rule_type text not null,rule_value text,enabled boolean default true,created_at timestamptz default now());
alter table public.watchlist_items enable row level security;alter table public.portfolio_items enable row level security;alter table public.alert_rules enable row level security;
create policy "own watchlist" on public.watchlist_items for all using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
create policy "own portfolio" on public.portfolio_items for all using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
create policy "own alerts" on public.alert_rules for all using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
create index if not exists watchlist_user_idx on public.watchlist_items(user_id);create index if not exists portfolio_user_idx on public.portfolio_items(user_id);create index if not exists alerts_user_idx on public.alert_rules(user_id);
