"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import Header from "@/components/Header";
import { ALERT_RULES_KEY, AlertRule } from "@/components/AlertRuleButton";
import { getSupabaseBrowserClient } from "@/lib/supabaseClient";

const LABELS:Record<AlertRule["type"],string>={"regime-change":"Any regime change","enters-awakening":"Enters Awakening","enters-volatile":"Enters Volatile","spark-above":"SparkScore threshold"};
type AlertRuleRow={coin_id:string;type:AlertRule["type"];threshold:number|null;created_at:string};
type AlertEvent={id:string;coin_id:string;title:string;body:string;delivered_email:boolean;created_at:string};
function readLocal():AlertRule[]{if(typeof window==="undefined")return[];try{return JSON.parse(localStorage.getItem(ALERT_RULES_KEY)||"[]") as AlertRule[]}catch{return[]}}
function writeLocal(rules:AlertRule[]){localStorage.setItem(ALERT_RULES_KEY,JSON.stringify(rules));}
function when(value:string){const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString(undefined,{dateStyle:"medium",timeStyle:"short"});}

export default function AlertsPage(){
 const[rules,setRules]=useState<AlertRule[]>([]),[events,setEvents]=useState<AlertEvent[]>([]),[loading,setLoading]=useState(true),[historyLoading,setHistoryLoading]=useState(false),[signedIn,setSignedIn]=useState(false),[status,setStatus]=useState("Checking account sync…"),[testState,setTestState]=useState<"idle"|"sending"|"sent"|"error">("idle"),[testMessage,setTestMessage]=useState(""),[removing,setRemoving]=useState<string|null>(null);

 async function loadHistory(){try{const supabase=getSupabaseBrowserClient();const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token){setEvents([]);return;}setHistoryLoading(true);const response=await fetch("/api/alert-history",{headers:{Authorization:`Bearer ${session.access_token}`}});const result=await response.json();if(response.ok)setEvents(result.events??[]);}finally{setHistoryLoading(false)}}
 async function load(){const local=readLocal();try{const supabase=getSupabaseBrowserClient();const{data:{user}}=await supabase.auth.getUser();if(!user){setSignedIn(false);setRules(local);setEvents([]);setStatus("Saved on this device. Sign in to sync alerts across devices.");return;}setSignedIn(true);const response=await supabase.from("alert_rules").select("coin_id,type,threshold,created_at").eq("user_id",user.id).eq("enabled",true).order("created_at",{ascending:false});if(response.error)throw response.error;const remote=((response.data??[]) as AlertRuleRow[]).map(r=>({coinId:r.coin_id,type:r.type,threshold:r.threshold??undefined,createdAt:r.created_at}));setRules(remote);setStatus(`Synced to your CoinSparkLine account · ${remote.length} cloud rule${remote.length===1?"":"s"}`);await loadHistory();}catch(err){setRules(local);setStatus(err instanceof Error?`Account sync unavailable: ${err.message}`:"Account sync unavailable. Showing device rules.");}finally{setLoading(false)}}
 useEffect(()=>{load();const reload=()=>load();window.addEventListener("csl-alert-rules-change",reload);return()=>window.removeEventListener("csl-alert-rules-change",reload)},[]);

 async function sendTestEmail(){setTestState("sending");setTestMessage("");try{const supabase=getSupabaseBrowserClient();const{data:{session},error}=await supabase.auth.getSession();if(error||!session?.access_token)throw new Error("Please sign in again before testing email delivery.");const response=await fetch("/api/test-alert",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`}});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result?.error||"Test email could not be sent.");setTestState("sent");setTestMessage("Test email sent. Check your inbox.");}catch(err){setTestState("error");setTestMessage(err instanceof Error?err.message:"Test email could not be sent.");}}
 async function remove(rule:AlertRule){const key=`${rule.coinId}:${rule.type}`;if(removing)return;setRemoving(key);const before=rules;setRules(before.filter(r=>!(r.coinId===rule.coinId&&r.type===rule.type)));writeLocal(readLocal().filter(r=>!(r.coinId===rule.coinId&&r.type===rule.type)));try{if(signedIn){const supabase=getSupabaseBrowserClient();const{data:{user}}=await supabase.auth.getUser();if(user){const{error}=await supabase.from("alert_rules").delete().eq("user_id",user.id).eq("coin_id",rule.coinId).eq("type",rule.type);if(error)throw error;}}setStatus("Alert removed.");window.dispatchEvent(new CustomEvent("csl-alert-rules-change"));}catch(err){setRules(before);setStatus(err instanceof Error?`Could not remove alert: ${err.message}`:"Could not remove alert.");}finally{setRemoving(null)}}
 const grouped=useMemo(()=>rules.reduce<Record<string,AlertRule[]>>((acc,r)=>{(acc[r.coinId]??=[]).push(r);return acc},{}),[rules]);

 return <div className="min-h-screen bg-[#fbfcff] text-slate-950"><Header/><main className="mx-auto max-w-5xl px-5 py-10 sm:px-6">
  <div className="mx-auto max-w-2xl text-center"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-violet-500">Signal alerts</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em]">Watch the change, not the noise.</h1><p className="mt-3 text-sm leading-6 text-slate-500">Create rules for regime flips, Awakening, Volatile entry or SparkScore thresholds.</p></div>
  <div className={`mx-auto mt-6 max-w-3xl rounded-2xl border px-4 py-3 ${signedIn?"border-emerald-100 bg-emerald-50":"border-slate-200 bg-white"}`}><div className="flex items-center justify-between gap-3"><p className={`text-[11px] leading-5 ${signedIn?"text-emerald-700":"text-slate-500"}`}><strong>{signedIn?"Account sync on":"Device-only mode"}:</strong> {status}</p>{!signedIn&&<Link href="/signin" className="shrink-0 rounded-full bg-slate-950 px-3 py-1.5 text-[10px] font-bold text-white">Sign in</Link>}</div></div>
  {signedIn&&<div className="mx-auto mt-4 max-w-3xl rounded-2xl border border-blue-100 bg-blue-50 px-4 py-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold text-blue-900">Email delivery test</p><p className="mt-1 text-[10px] text-blue-700">Send a harmless test message to your signed-in email.</p></div><button onClick={sendTestEmail} disabled={testState==="sending"} className="shrink-0 rounded-full bg-blue-600 px-4 py-2 text-[10px] font-bold text-white disabled:opacity-50">{testState==="sending"?"Sending…":"Send test email"}</button></div>{testMessage&&<p className={`mt-2 text-[10px] ${testState==="sent"?"text-emerald-700":"text-rose-600"}`}>{testMessage}</p>}</div>}
  <section className="mx-auto mt-4 max-w-3xl rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><p className="text-sm font-semibold text-slate-900">Armed alerts</p><p className="mt-1 text-[10px] text-slate-400">Remove buttons update immediately and sync in the background.</p></div></div>{loading?<div className="py-10 text-center text-xs text-slate-400">Loading alerts…</div>:rules.length?<div className="space-y-4">{Object.entries(grouped).map(([coinId,coinRules])=><div key={coinId} className="rounded-2xl border border-slate-200 bg-slate-50/70 p-4"><div className="flex items-center justify-between gap-3"><div><Link href={`/coin/${coinId}`} className="text-base font-semibold capitalize text-slate-900 hover:text-blue-600">{coinId.replace(/-/g," ")}</Link><p className="mt-1 text-[10px] uppercase tracking-[.14em] text-slate-400">{coinRules.length} armed condition{coinRules.length>1?"s":""}</p></div><Link href={`/coin/${coinId}`} className="rounded-full border border-slate-200 bg-white px-3 py-1.5 text-[10px] font-semibold text-slate-500">Open coin</Link></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{coinRules.map(r=>{const key=`${r.coinId}:${r.type}`;return <div key={key} className="flex items-center justify-between gap-3 rounded-xl border border-slate-200 bg-white px-3 py-3"><div><p className="text-xs font-semibold text-slate-800">{LABELS[r.type]}</p><p className="mt-1 text-[10px] text-slate-400">{r.type==="spark-above"?`Trigger at SparkScore ${r.threshold??75}`:"Active rule"}</p></div><button disabled={!!removing} onClick={()=>remove(r)} className="min-w-[76px] rounded-lg bg-rose-50 px-3 py-2 text-[10px] font-bold text-rose-600 disabled:opacity-50">{removing===key?"Removing…":"Remove"}</button></div>})}</div></div>)}</div>:<div className="py-10 text-center"><p className="text-sm font-semibold text-slate-700">No alert rules yet.</p><p className="mt-1 text-xs text-slate-400">Open a coin and press Alert to choose a condition.</p></div>}</section>
  {signedIn&&<section className="mx-auto mt-4 max-w-3xl rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-slate-900">Recent alert history</p><p className="mt-1 text-[10px] text-slate-400">Real signal events detected for your account.</p></div><button onClick={loadHistory} disabled={historyLoading} className="rounded-full border border-slate-200 px-3 py-1.5 text-[10px] font-semibold text-slate-500 disabled:opacity-50">{historyLoading?"Refreshing…":"Refresh"}</button></div>{historyLoading&&!events.length?<div className="py-8 text-center text-xs text-slate-400">Loading history…</div>:events.length?<div className="mt-4 space-y-2">{events.map(e=><div key={e.id} className="rounded-2xl border border-slate-200 bg-slate-50/60 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold text-slate-900">{e.title}</p><p className="mt-1 text-[11px] leading-5 text-slate-500">{e.body}</p></div><span className={`shrink-0 rounded-full px-2 py-1 text-[9px] font-bold ${e.delivered_email?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{e.delivered_email?"EMAILED":"DETECTED"}</span></div><div className="mt-3 flex items-center justify-between text-[10px] text-slate-400"><span>{when(e.created_at)}</span><Link href={`/coin/${e.coin_id}`} className="font-semibold text-blue-600">Open coin →</Link></div></div>)}</div>:<div className="py-8 text-center"><p className="text-xs font-semibold text-slate-600">No real alert events yet.</p><p className="mt-1 text-[10px] text-slate-400">They will appear here after an armed condition actually triggers.</p></div>}</section>}
  <div className="mx-auto mt-4 max-w-3xl rounded-2xl border border-emerald-100 bg-emerald-50 px-4 py-3"><p className="text-[11px] leading-5 text-emerald-800"><strong>Automatic email delivery: active.</strong> Scheduled scans check armed cloud rules and email you when a real condition triggers.</p></div>
  <div className="mt-5 text-center"><Link href="/" className="text-xs font-semibold text-slate-500 hover:text-slate-900">← Back to market</Link></div>
 </main></div>;
}
