import type {Metadata,Viewport} from "next";
import "./globals.css";
import "./csl2.css";
import "../styles/design-system.css";
import "../styles/ui-primitives.css";
import "../styles/app-shell.css";
import "../styles/homepage.css";
import "../styles/homepage-phase4.css";
import "../styles/live-page.css";
import "../styles/discovery-pages.css";
import "../styles/coin-detail-reference.css";
import "../styles/personal-intelligence.css";
import "../styles/secondary-discovery.css";
import {CurrencyProvider} from "@/components/CurrencyProvider";
import CookieConsent from "@/components/CookieConsent";
import CoinPageWatchlistDock from "@/components/CoinPageWatchlistDock";
import PWARegister from "@/components/PWARegister";
export const metadata:Metadata={title:"CoinSparkLine — See the market before it feels obvious.",description:"A clearer way to see crypto market behaviour, momentum and regime change.",manifest:"/manifest.webmanifest",applicationName:"CoinSparkLine",appleWebApp:{capable:true,title:"CoinSparkLine",statusBarStyle:"default"},icons:{icon:"/pwa-icon.svg",apple:"/pwa-icon.svg"},formatDetection:{telephone:false}};
export const viewport:Viewport={themeColor:"#2457d6",width:"device-width",initialScale:1,viewportFit:"cover"};
export default function RootLayout({children}:LayoutProps<"/">){return <html lang="en" className="h-full"><body id="top" className="csl-app min-h-full flex flex-col antialiased"><CurrencyProvider>{children}<CoinPageWatchlistDock/><PWARegister/><CookieConsent/></CurrencyProvider></body></html>}
