"use client";
import {FormEvent,useEffect,useState} from"react";import Link from"next/link";import{createClient,supabaseConfigured}from"@/lib/supabase/client";
type Rule={id:number;coin_id:string;rule_type:string;rule_value:string|null;enabled:boolean;last_triggered_at:string|null};
const TYPES=[['regime-change','Any regime change'],['entered-awakening','Entered Awakening'],['spark-threshold','SparkScore crosses threshold'],['heating-up','Heating Up']] as const;
export default function AlertManager(){const[uid,setUid]=useState<string|null>(null),[rules,setRules]=useState<Rule[]>([]),[coin,setCoin]=useState('bitcoin'),[type,setType]=useState('regime-change'),[value,setValue]=useState('70'),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');const supabase=supabaseConfigured?createClient():null;
 async function load(){if(!supabase)return;const{data:{user}}=await supabase.auth.getUser();setUid(user?.id??null);if(!user)return;const{data}=await supabase.from('alert_rules').select('id,coin_id,rule_type,rule_value,enabled,last_triggered_at').order('created_at',{ascending:false});setRules((data??[])as Rule[])}
 useEffect(()=>{if(supabaseConfigured)void load()},[]);
 async function add(e:FormEvent){e.preventDefault();if(!uid||!supabase)return;setBusy(true);setMsg('');const payload={user_id:uid,coin_id:coin.trim().toLowerCase(),rule_type:type,rule_value:type==='spark-threshold'?value:null,enabled:true};const{error}=await supabase.from('alert_rules').insert(payload);setBusy(false);if(error)setMsg(error.message);else{setMsg('Alert armed.');await load()}}
 async function toggle(r:Rule){if(!supabase)return;await supabase.from('alert_rules').update({enabled:!r.enabled}).eq('id',r.id);await load()}
 async function remove(id:number){if(!supabase)return;await supabase.from('alert_rules').delete().eq('id',id);await load()}
 if(!supabaseConfigured)return <div className="mx-auto mt-8 max-w-xl rounded-2xl border border-amber-200 bg-amber-50/60 p-6 text-center"><h2 className="text-lg font-semibold text-slate-900">Alerts are being configured</h2><p className="mt-2 text-sm text-slate-600">Account alerts will activate after the Supabase environment variables are added in Vercel.</p></div>;
 if(uid===null)return <div className="mx-auto mt-8 max-w-xl rounded-2xl border border-slate-200 bg-white p-6 text-center"><h2 className="text-lg font-semibold">Sign in to receive alerts</h2><p className="mt-2 text-sm text-slate-500">Email delivery requires a CoinSparkLine account.</p><Link href="/signin" className="mt-4 inline-flex rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white">Sign in</Link></div>;
 return <div className="mx-auto mt-7 max-w-3xl"><form onSubmit={add} className="grid gap-2 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-[1fr_1.4fr_.7fr_auto]"><input value={coin} onChange={e=>setCoin(e.target.value)} placeholder="Coin id, e.g. zcash" className="rounded-lg border border-slate-200 px-3 py-2 text-sm"/><select value={type} onChange={e=>setType(e.target.value)} className="rounded-lg border border-slate-200 px-3 py-2 text-sm">{TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{type==='spark-threshold'?<input value={value} onChange={e=>setValue(e.target.value)} inputMode="numeric" className="rounded-lg border border-slate-200 px-3 py-2 text-sm" placeholder="70"/>:<div className="hidden sm:block"/>}<button disabled={busy} className="rounded-lg bg-gradient-to-r from-blue-600 to-violet-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Arm alert</button></form>{msg&&<p className="mt-2 text-center text-xs text-slate-500">{msg}</p>}<section className="mt-4 overflow-hidden rounded-2xl border border-slate-200 bg-white">{rules.length?rules.map(r=><div key={r.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-4 py-3 last:border-0"><div><Link href={`/coin/${r.coin_id}`} className="text-sm font-semibold capitalize hover:text-violet-600">{r.coin_id.replace(/-/g,' ')}</Link><p className="mt-1 text-[9px] uppercase tracking-wider text-slate-400">{TYPES.find(x=>x[0]===r.rule_type)?.[1]??r.rule_type}{r.rule_type==='spark-threshold'&&r.rule_value?` · ${r.rule_value}`:''}</p>{r.last_triggered_at&&<p className="mt-1 text-[9px] text-slate-400">Last triggered {new Date(r.last_triggered_at).toLocaleString()}</p>}</div><div className="flex items-center gap-2"><button onClick={()=>toggle(r)} className={`rounded-full px-2.5 py-1 text-[9px] font-bold ${r.enabled?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{r.enabled?'ARMED':'PAUSED'}</button><button onClick={()=>remove(r.id)} className="text-[9px] font-semibold text-rose-500">Remove</button></div></div>):<p className="p-8 text-center text-sm text-slate-400">No account alerts yet.</p>}</section></div>}
