"use client";
import Link from "next/link";
import {FormEvent,useState} from "react";
import {getSupabaseBrowserClient} from "@/lib/supabaseClient";

export default function AuthPreview({mode}:{mode:"signin"|"signup"}){
 const signup=mode==="signup";
 const[name,setName]=useState("");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[showPassword,setShowPassword]=useState(false);
 const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setMessage("");try{const supabase=getSupabaseBrowserClient();if(signup){const{error}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{name:name.trim()}}});if(error)throw error;setMessage("Account created. Check your email if confirmation is enabled, then sign in.");}else{const{error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;setMessage("Signed in successfully. Loading your CoinSparkLine account…");setTimeout(()=>{window.location.href="/"},550);}}catch(err){setMessage(err instanceof Error?err.message:"Authentication failed");}finally{setBusy(false)}}
 return <main className="mx-auto flex min-h-[68vh] max-w-[460px] items-center px-4 py-8 sm:py-10"><div className="w-full rounded-[24px] border border-slate-200 bg-white p-5 shadow-[0_14px_45px_rgba(20,35,75,.07)] sm:p-7"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-slate-400">CoinSparkLine account</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] text-slate-950">{signup?"Create your account":"Welcome back"}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{signup?"Create an account to sync alerts and your watchlist across devices.":"Sign in to access synced alerts, your watchlist and account tools."}</p><form onSubmit={submit} className="mt-6 space-y-3">{signup&&<input required autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="Name" className="h-12 w-full rounded-xl border border-slate-200 px-3 text-base outline-none focus:border-violet-300 focus:ring-2 focus:ring-violet-100 sm:text-sm"/>}<input required autoComplete="email" inputMode="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" className="h-12 w-full rounded-xl border border-slate-200 px-3 text-base outline-none focus:border-violet-300 focus:ring-2 focus:ring-violet-100 sm:text-sm"/><div className="relative"><input required minLength={6} autoComplete={signup?"new-password":"current-password"} type={showPassword?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" className="h-12 w-full rounded-xl border border-slate-200 px-3 pr-16 text-base outline-none focus:border-violet-300 focus:ring-2 focus:ring-violet-100 sm:text-sm"/><button type="button" onClick={()=>setShowPassword(v=>!v)} className="absolute right-2 top-1/2 -translate-y-1/2 rounded-lg px-2.5 py-2 text-[10px] font-semibold text-slate-500">{showPassword?"Hide":"Show"}</button></div><button disabled={busy} className="h-12 w-full rounded-xl bg-gradient-to-r from-blue-600 to-violet-600 px-4 text-sm font-semibold text-white shadow-sm disabled:cursor-wait disabled:opacity-55">{busy?"Please wait…":signup?"Sign up":"Sign in"}</button></form>{message&&<div role="status" className="mt-3 rounded-xl bg-slate-50 px-3 py-2.5 text-xs leading-5 text-slate-700">{message}</div>}<p className="mt-5 text-center text-xs text-slate-500">{signup?"Already have an account? ":"New to CoinSparkLine? "}<Link href={signup?"/signin":"/signup"} className="font-semibold text-blue-600">{signup?"Sign in":"Sign up"}</Link></p></div></main>
}
