"use client";
import Link from "next/link";
import {FormEvent,useState} from "react";
import {useSearchParams} from "next/navigation";
import {getSupabaseBrowserClient} from "@/lib/supabaseClient";
import Clean2030Controls from "@/components/Clean2030Controls";

export default function CleanAuth2030({mode}:{mode:"signin"|"signup"}){
 const signup=mode==="signup";const params=useSearchParams();const requested=params.get("next")||"/portfolio";const next=requested.startsWith("/")&&!requested.startsWith("//")?requested:"/portfolio";
 const[name,setName]=useState("");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[error,setError]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setMessage("");setError(false);try{const supabase=getSupabaseBrowserClient();if(signup){const{data,error}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{name:name.trim()}}});if(error)throw error;if(data.session)window.location.href=next;else setMessage("Account created. Check your email to confirm it, then sign in.");}else{const{error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;window.location.href=next}}catch(err){setError(true);setMessage(err instanceof Error?err.message:"Authentication failed")}finally{setBusy(false)}}
 return <div className="clean2030 clean2030-auth-page"><header className="clean2030-top"><Link href="/crypto" className="clean2030-brand">Coin<span>SparkLine</span></Link><nav className="clean2030-nav"><Link href="/crypto">CRYPTO</Link><Link href="/nft">NFT</Link><Link href="/portfolio">PORTFOLIO</Link></nav><Clean2030Controls/></header><main className="clean2030-auth-wrap"><section className="clean2030-auth-card"><span className="clean2030-kicker">{signup?"Create account":"Welcome back"}</span><h1>{signup?"Create your CoinSparkLine account.":"Sign in to CoinSparkLine."}</h1><p>{signup?"Save your portfolio securely and keep it synced across your devices.":"Open your saved portfolio and keep tracking crypto in one place."}</p><form onSubmit={submit}>{signup?<label>Name<input required autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label>:null}<label>Email<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input required minLength={6} type="password" autoComplete={signup?"new-password":"current-password"} value={password} onChange={e=>setPassword(e.target.value)}/></label>{!signup?<div className="clean2030-auth-inline"><Link href="/forgot-password">Forgot password?</Link></div>:null}<button disabled={busy}>{busy?"PLEASE WAIT…":signup?"CREATE ACCOUNT":"SIGN IN"}</button></form>{message?<div className="clean2030-auth-message" data-error={error}>{message}</div>:null}{signup?<p className="clean2030-auth-switch">Already have an account? <Link href={`/signin?next=${encodeURIComponent(next)}`}>Sign in</Link></p>:<div className="clean2030-auth-actions"><span>New to CoinSparkLine?</span><Link className="clean2030-auth-create" href={`/signup?next=${encodeURIComponent(next)}`}>CREATE ACCOUNT</Link></div>}</section></main></div>
}
