"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { DisplayCurrency, useCurrency } from "@/components/CurrencyProvider";

function LogoMark(){return <span aria-hidden="true" className="shrink-0"><svg viewBox="0 0 94 38" width="54" height="28" fill="none"><defs><linearGradient id="csl-header-signal" x1="3" y1="19" x2="91" y2="19" gradientUnits="userSpaceOnUse"><stop offset="0" stopColor="#2F80F7"/><stop offset=".5" stopColor="#7957E8"/><stop offset="1" stopColor="#E33B96"/></linearGradient></defs><path d="M4 21H30C34 21 36 20 38 16L45 4L53 34L61 19C62.5 16.5 64.5 15 68 15H78" stroke="url(#csl-header-signal)" strokeWidth="4.3" strokeLinecap="round" strokeLinejoin="round"/><circle cx="84" cy="15" r="4.3" fill="#D84AA0"/></svg></span>}
function Wordmark(){return <span className="whitespace-nowrap text-[1.2rem] leading-none tracking-[-.05em] sm:text-[1.35rem]"><b className="font-[780] text-[#0B1224]">Coin</b><span className="bg-gradient-to-r from-blue-500 via-violet-500 to-pink-500 bg-clip-text font-semibold text-transparent">SparkLine</span></span>}

export default function Header(){
  const pathname=usePathname(); const{currency,setCurrency}=useCurrency(); const[open,setOpen]=useState(false);
  const navigation=[{href:"/",label:"Market"},{href:"/watchlist",label:"Watchlist"},{href:"/portfolio",label:"Portfolio"},{href:"/compare",label:"Compare"},{href:"/alerts",label:"Alerts"},{href:"/about",label:"About"}];
  return <header id="top" className="csl-site-header relative z-40 bg-white/95 backdrop-blur"><div className="mx-auto flex min-h-[4rem] max-w-[1390px] items-center justify-between gap-3 px-4 sm:min-h-[4.35rem] sm:px-5">
    <div className="flex min-w-0 items-center gap-4 xl:gap-7"><Link href="/" className="flex shrink-0 items-center gap-1.5" aria-label="CoinSparkLine home"><LogoMark/><Wordmark/></Link><p className="hidden whitespace-nowrap text-[12px] font-semibold tracking-[-.02em] text-slate-800 lg:block xl:text-[13px]">Track the calm. <span className="bg-gradient-to-r from-blue-500 via-violet-500 to-pink-500 bg-clip-text text-transparent">Catch the move.</span></p></div>
    <div className="flex min-w-0 items-center gap-2"><nav className="hidden items-center gap-0.5 xl:flex" aria-label="Primary navigation">{navigation.map(item=>{const active=pathname===item.href||item.href!=="/"&&pathname.startsWith(item.href+"/");return <Link key={item.href} href={item.href} className={`rounded-full px-2.5 py-1.5 text-[10px] font-semibold transition ${active?"bg-slate-950 text-white":"text-slate-600 hover:bg-slate-100 hover:text-slate-950"}`} aria-current={active?"page":undefined}>{item.label}</Link>})}</nav>
      <div className="hidden items-center rounded-full border border-slate-200 bg-white p-0.5 2xl:flex" aria-label="Display currency">{(["USD","GBP","EUR"] as DisplayCurrency[]).map(code=><button key={code} type="button" onClick={()=>setCurrency(code)} className={`rounded-full px-2 py-0.5 text-[8px] font-semibold ${currency===code?"bg-slate-950 text-white":"text-slate-500"}`} aria-pressed={currency===code}>{code==="USD"?"$":code==="GBP"?"£":"€"}</button>)}</div>
      <Link href="/signin" className="hidden rounded-lg border border-slate-200 bg-white px-3 py-2 text-[10px] font-semibold text-slate-700 hover:border-slate-300 sm:inline-flex">Sign in</Link><Link href="/signup" className="hidden rounded-lg bg-gradient-to-r from-blue-600 to-violet-600 px-3 py-2 text-[10px] font-semibold text-white shadow-sm hover:shadow-md sm:inline-flex">Sign up</Link>
      <select value={currency} onChange={e=>setCurrency(e.target.value as DisplayCurrency)} className="rounded-full border border-slate-200 bg-white px-2 py-1 text-[10px] font-semibold text-slate-700 2xl:hidden" aria-label="Display currency"><option value="USD">$</option><option value="GBP">£</option><option value="EUR">€</option></select>
      <button type="button" onClick={()=>setOpen(v=>!v)} className="flex h-9 w-9 items-center justify-center rounded-full border border-slate-200 bg-white text-lg text-slate-800 sm:hidden" aria-label="Toggle menu" aria-expanded={open}>{open?"×":"☰"}</button>
    </div>
  </div>
  <div className="hidden border-t border-slate-100 sm:block xl:hidden"><nav className="mx-auto flex max-w-[1390px] gap-1 overflow-x-auto px-5 py-1.5" aria-label="Tablet navigation">{navigation.map(item=><Link key={item.href} href={item.href} className="shrink-0 rounded-full px-2.5 py-1 text-[9px] font-semibold text-slate-600 hover:bg-slate-100">{item.label}</Link>)}</nav></div>
  {open&&<div className="absolute left-0 right-0 top-full border-t border-slate-100 bg-white px-4 py-3 shadow-lg sm:hidden"><nav className="grid grid-cols-2 gap-2" aria-label="Mobile navigation">{navigation.map(item=><Link key={item.href} href={item.href} onClick={()=>setOpen(false)} className="rounded-xl bg-slate-50 px-4 py-3 text-[12px] font-semibold text-slate-700">{item.label}</Link>)}</nav><div className="mt-3 grid grid-cols-2 gap-2"><Link href="/signin" onClick={()=>setOpen(false)} className="rounded-xl border border-slate-200 px-4 py-3 text-center text-[11px] font-semibold text-slate-700">Sign in</Link><Link href="/signup" onClick={()=>setOpen(false)} className="rounded-xl bg-gradient-to-r from-blue-600 to-violet-600 px-4 py-3 text-center text-[11px] font-semibold text-white">Sign up</Link></div></div>}
  </header>;
}
