"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { DisplayCurrency, useCurrency } from "@/components/CurrencyProvider";

function LogoMark(){return <span aria-hidden="true" className="shrink-0"><svg viewBox="0 0 94 38" width="42" height="21" fill="none"><defs><linearGradient id="csl-header-signal" x1="3" y1="19" x2="91" y2="19" gradientUnits="userSpaceOnUse"><stop offset="0" stopColor="#2F80F7"/><stop offset=".5" stopColor="#7957E8"/><stop offset="1" stopColor="#E33B96"/></linearGradient></defs><path d="M4 21H30C34 21 36 20 38 16L45 4L53 34L61 19C62.5 16.5 64.5 15 68 15H78" stroke="url(#csl-header-signal)" strokeWidth="4.3" strokeLinecap="round" strokeLinejoin="round"/><circle cx="84" cy="15" r="4.3" fill="#D84AA0"/></svg></span>}
function Wordmark(){return <span className="whitespace-nowrap text-[.94rem] leading-none tracking-[-.045em]"><b className="font-[760] text-[#0B1224]">Coin</b><span className="bg-gradient-to-r from-blue-500 via-violet-500 to-pink-500 bg-clip-text font-semibold text-transparent">SparkLine</span></span>}
export default function Header(){const pathname=usePathname();const{currency,setCurrency}=useCurrency();const navigation=[{href:"/",label:"Market"},{href:"/watchlist",label:"Watchlist"},{href:"/compare",label:"Compare"},{href:"/alerts",label:"Alerts"},{href:"/about",label:"About"}];return <header id="top" className="csl-site-header"><div className="csl-header-inner flex min-h-[3.6rem] items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3 lg:gap-5"><Link href="/" className="flex shrink-0 items-center gap-1.5" aria-label="CoinSparkLine home"><LogoMark/><span className="hidden min-[420px]:inline"><Wordmark/></span></Link><p className="hidden whitespace-nowrap text-[10px] font-semibold tracking-[-.015em] text-slate-800 xl:block">Track the calm. <span className="bg-gradient-to-r from-blue-500 via-violet-500 to-pink-500 bg-clip-text text-transparent">Catch the move.</span></p></div><div className="flex items-center gap-2"><nav className="csl-primary-nav" aria-label="Primary navigation">{navigation.map(item=>{const active=pathname===item.href||item.href!=="/"&&pathname.startsWith(item.href+"/");return <Link key={item.href} href={item.href} className={`csl-nav-link${active?" csl-nav-link--active":""}`} style={{minHeight:"1.65rem",padding:".34rem .52rem",fontSize:".68rem"}} aria-current={active?"page":undefined}>{item.label}</Link>})}</nav><div className="hidden items-center rounded-full border border-slate-200/80 bg-white/85 p-0.5 sm:flex" aria-label="Display currency">{(["USD","GBP","EUR"] as DisplayCurrency[]).map(code=><button key={code} type="button" onClick={()=>setCurrency(code)} className={`rounded-full px-2 py-0.5 text-[9px] font-semibold ${currency===code?"bg-slate-950 text-white":"text-slate-500"}`} aria-pressed={currency===code}>{code==="USD"?"$":code==="GBP"?"£":"€"} {code}</button>)}</div><select value={currency} onChange={e=>setCurrency(e.target.value as DisplayCurrency)} className="rounded-full border border-slate-200 bg-white px-2 py-1 text-[10px] font-semibold text-slate-700 sm:hidden" aria-label="Display currency"><option value="USD">$ USD</option><option value="GBP">£ GBP</option><option value="EUR">€ EUR</option></select></div></div></header>}
