"use client";

import Link from "next/link";
import {useMemo,useState} from "react";
import {Coin} from "@/types/coin";
import {getSignalTier,TIER_CONFIG} from "@/lib/tiers";
import {getSparkScore} from "@/lib/sparkScore";
import CurrencyAmount from "@/components/CurrencyAmount";
import WatchlistButton from "@/components/WatchlistButton";
import AlertRuleButton from "@/components/AlertRuleButton";
import MarketHeatmap from "@/components/MarketHeatmap";

type RadarMode="heating"|"cooling"|"flipped"|"strongest";

function PulseGraphic(){return <svg viewBox="0 0 720 180" fill="none" aria-hidden="true"><defs><linearGradient id="pulse" x1="30" y1="90" x2="690" y2="90"><stop stopColor="#06B6D4"/><stop offset=".36" stopColor="#1677FF"/><stop offset=".7" stopColor="#4F46E5"/><stop offset="1" stopColor="#8B5CF6"/></linearGradient><filter id="glow"><feGaussianBlur stdDeviation="7" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><path d="M28 111C78 108 112 103 153 104C196 105 209 76 250 87C292 98 320 126 359 106C397 86 421 68 453 77C487 87 502 106 533 96C568 85 594 91 621 91C646 91 665 78 692 67" stroke="url(#pulse)" strokeWidth="8" strokeLinecap="round" opacity=".12" filter="url(#glow)"/><path d="M28 111C78 108 112 103 153 104C196 105 209 76 250 87C292 98 320 126 359 106C397 86 421 68 453 77C487 87 502 106 533 96C568 85 594 91 621 91C646 91 665 78 692 67" stroke="url(#pulse)" strokeWidth="3.4" strokeLinecap="round"/><circle cx="692" cy="67" r="7" fill="#4F46E5"/><circle cx="692" cy="67" r="14" fill="#4F46E5" opacity=".12"/></svg>}

function regimeTone(tier:string){if(tier==="volatile")return{bg:"#fff1f2",text:"#be123c"};if(tier==="awakening")return{bg:"#fff7ed",text:"#c2410c"};if(tier==="building")return{bg:"#fffbeb",text:"#a16207"};return{bg:"#ecfdf5",text:"#047857"}}

export default function HomeV2({coins,updatedLabel}:{coins:Coin[];updatedLabel?:string}){
 const[mode,setMode]=useState<RadarMode>("heating");const[query,setQuery]=useState("");const[visible,setVisible]=useState(30);
 const eligible=useMemo(()=>coins.filter(c=>!["usdt","usdc","dai","busd","tusd","usdp"].includes(c.symbol.toLowerCase())),[coins]);
 const radar=useMemo(()=>{const fresh=(a:Coin,b:Coin)=>a.streakDays-b.streakDays||b.confidencePct-a.confidencePct;if(mode==="heating")return eligible.filter(c=>["awakening","volatile"].includes(getSignalTier(c))).sort(fresh).slice(0,8);if(mode==="cooling")return eligible.filter(c=>["building","calm"].includes(getSignalTier(c))).sort(fresh).slice(0,8);if(mode==="flipped")return eligible.filter(c=>c.streakDays<=2).sort(fresh).slice(0,8);return[...eligible].sort((a,b)=>getSparkScore(b).score-getSparkScore(a).score).slice(0,8)},[eligible,mode]);
 const discovered=useMemo(()=>{const q=query.trim().toLowerCase();return [...eligible].filter(c=>!q||c.name.toLowerCase().includes(q)||c.symbol.toLowerCase().includes(q)).sort((a,b)=>(a.marketCapRank??9999)-(b.marketCapRank??9999))},[eligible,query]);
 const awakening=eligible.filter(c=>getSignalTier(c)==="awakening").length;const volatile=eligible.filter(c=>getSignalTier(c)==="volatile").length;const calm=eligible.filter(c=>getSignalTier(c)==="calm").length;const strongest=[...eligible].sort((a,b)=>getSparkScore(b).score-getSparkScore(a).score)[0];
 const modes:[RadarMode,string][]=[["heating","Heating Up"],["cooling","Cooling Down"],["flipped","Just Flipped"],["strongest","Strongest"]];
 return <>
  <section className="csl2-hero"><div className="csl-shell csl2-hero-grid"><div><p className="csl-kicker">CoinSparkLine 2.0</p><h1 className="csl-title mt-4">See the market<br/><span className="csl-gradient-text">before it feels obvious.</span></h1><p className="csl-subtitle mt-6 max-w-[650px]">CoinSparkLine turns crypto market behaviour into a calmer signal: what is waking up, what is overheating, and what deserves your attention next.</p><div className="mt-7 flex flex-wrap gap-3"><a href="#radar" className="csl-btn-primary">Explore Spark Radar <span>→</span></a><a href="#heatmap" className="csl-btn-soft">Open market heatmap</a></div></div><div className="csl2-pulse-card"><div className="relative z-10 flex items-start justify-between gap-4"><div><p className="csl-kicker">Market Pulse</p><h2 className="mt-2 text-[28px] font-extrabold tracking-[-.045em]">{volatile>awakening?"Momentum is running hot.":awakening>0?"Momentum is starting to wake up.":"The market is mostly calm."}</h2><p className="mt-2 text-[12px] font-medium text-slate-500">Signals {updatedLabel?.toLowerCase()||"from the latest snapshot"}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-[10px] font-extrabold text-emerald-700">● LIVE</span></div><div className="csl2-pulse-line relative z-10"><PulseGraphic/></div><div className="csl2-metrics relative z-10"><div className="csl2-metric"><strong>{eligible.length}</strong><span>Assets tracked</span></div><div className="csl2-metric"><strong>{awakening}</strong><span>Awakening</span></div><div className="csl2-metric"><strong>{volatile}</strong><span>Volatile</span></div><div className="csl2-metric"><strong>{strongest?getSparkScore(strongest).score:"—"}</strong><span>Top SparkScore</span></div></div></div></div></section>

  <section id="radar" className="csl2-section"><div className="csl-shell"><div className="csl2-section-head"><div><p className="csl-kicker">Flagship signal view</p><h2 className="csl-section-title mt-2">Spark Radar</h2><p className="csl-subtitle mt-2">The coins showing the clearest change in market behaviour right now.</p></div><div className="csl2-segments">{modes.map(([m,label])=><button key={m} onClick={()=>setMode(m)} className={`csl2-segment ${mode===m?"is-active":""}`}>{label}</button>)}</div></div><div className="csl2-radar-grid">{radar.map(coin=>{const spark=getSparkScore(coin);const tier=getSignalTier(coin);const tone=regimeTone(tier);const positive=coin.change24hPct>=0;return <article key={coin.id} className="csl2-radar-card"><div className="absolute right-3 top-3 z-10"><WatchlistButton coinId={coin.id} compact/></div><Link href={`/coin/${coin.id}`} className="block"><div className="csl2-coin-head pr-9">{coin.logoUrl?<img src={coin.logoUrl} alt="" className="csl2-coin-logo"/>:<span className="csl2-coin-logo grid place-items-center bg-slate-100 text-[10px] font-bold text-slate-500">{coin.symbol.slice(0,3)}</span>}<div className="csl2-coin-name"><strong>{coin.name}</strong><span>{coin.symbol}</span></div></div><div className="csl2-price-row"><div className="csl2-price"><CurrencyAmount usd={coin.price}/></div><span className={`csl2-change ${positive?"up":"down"}`}>{positive?"+":""}{coin.change24hPct.toFixed(2)}%</span></div><div className="csl2-score"><div className="csl2-score-top"><span>SparkScore</span><b>{spark.label}</b></div><div className="csl2-score-value"><strong>{spark.score}</strong><span>/100</span></div><div className="csl2-score-bar"><i style={{width:`${spark.score}%`}}/></div></div><div className="csl2-regime" style={{background:tone.bg}}><b style={{color:tone.text}}>{TIER_CONFIG[tier].label}</b><span>{coin.confidencePct.toFixed(0)}% confidence</span></div></Link><div className="csl2-card-actions"><Link href={`/coin/${coin.id}`} className="csl-btn-soft !min-h-[36px] !px-3 !text-[10px]">View signal</Link><div className="[&>button]:min-h-[36px] [&>button]:w-full [&>button]:rounded-full [&>button]:border [&>button]:border-indigo-100 [&>button]:bg-white [&>button]:px-3 [&>button]:text-[10px] [&>button]:font-bold [&>button]:text-indigo-600"><AlertRuleButton coinId={coin.id} compact/></div></div></article>})}</div></div></section>

  <MarketHeatmap coins={eligible}/>

  <section id="discover" className="csl2-section pb-16"><div className="csl-shell"><div className="csl2-section-head"><div><p className="csl-kicker">Explore everything</p><h2 className="csl-section-title mt-2">Discover</h2><p className="csl-subtitle mt-2">A clean view across the full tracked market — not just a top 30.</p></div><div className="text-right"><p className="text-[28px] font-extrabold tracking-[-.04em]">{eligible.length}</p><p className="text-[10px] font-bold uppercase tracking-[.1em] text-slate-400">Tracked assets</p></div></div><div className="csl2-discover-shell"><input className="csl2-search" placeholder="Search Bitcoin, Zcash, Solana…" value={query} onChange={e=>{setQuery(e.target.value);setVisible(30)}}/><div className="csl2-discovery-grid">{discovered.slice(0,visible).map(coin=>{const positive=coin.change24hPct>=0;const spark=getSparkScore(coin);return <Link key={coin.id} href={`/coin/${coin.id}`} className="csl2-mini-coin"><div className="csl2-coin-head">{coin.logoUrl?<img src={coin.logoUrl} alt="" className="h-8 w-8 shrink-0 rounded-full object-contain"/>:<span className="h-8 w-8 shrink-0 rounded-full bg-slate-100"/>}<div className="csl2-coin-name"><strong>{coin.name}</strong><span>{coin.symbol}{coin.marketCapRank?` · #${coin.marketCapRank}`:""}</span></div></div><div className="price"><CurrencyAmount usd={coin.price}/></div><div className="meta"><span className={positive?"text-emerald-600":"text-rose-600"}>{positive?"+":""}{coin.change24hPct.toFixed(2)}%</span><span>SPARK {spark.score}</span></div></Link>})}</div>{visible<discovered.length&&<div className="mt-5 text-center"><button className="csl-btn-soft" onClick={()=>setVisible(v=>Math.min(v+30,discovered.length))}>Show 30 more</button></div>}</div></div></section>
 </>;
}
