"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
import FilterPills from "@/components/FilterPills";
import ScannerCard from "@/components/ScannerCard";
import MarketBreadthCard,{MarketBreadthCoin} from "@/components/MarketBreadthCard";
import SortControl,{SortOption} from "@/components/SortControl";
import CurrencyAmount from "@/components/CurrencyAmount";
import WatchlistButton from "@/components/WatchlistButton";
import AlertRuleButton from "@/components/AlertRuleButton";
import {Coin} from "@/types/coin";
import {getSignalTier,TIER_CONFIG,SignalTier} from "@/lib/tiers";
import {getSparkScore} from "@/lib/sparkScore";
import {isStablecoin} from "@/lib/categories";

interface Props{coins:Coin[];previousCoins?:Coin[];previousScannedAt?:string;marketCoins?:MarketBreadthCoin[];categories:string[];updatedLabel?:string}
type RadarMode="heating"|"cooling"|"flipped"|"strongest";
const LEVEL:Record<SignalTier,number>={calm:0,building:1,awakening:2,volatile:3};
function sortCoins(coins:Coin[],sort:SortOption){const s=[...coins];if(sort==="signal-strength")return s.sort((a,b)=>b.confidencePct-a.confidencePct);if(sort==="biggest-move")return s.sort((a,b)=>Math.abs(b.change24hPct)-Math.abs(a.change24hPct));if(sort==="market-cap")return s.sort((a,b)=>(b.marketCap??0)-(a.marketCap??0));return s.sort((a,b)=>a.medianDaysToFlip-b.medianDaysToFlip)}
function CompactTitle({title}:{title:string}){return <div className="text-[13px] font-extrabold uppercase tracking-[.015em] text-slate-950 sm:text-[14px]">{title}</div>}
function formatCompact(n:number){if(n>=1e12)return`$${(n/1e12).toFixed(2)}T`;if(n>=1e9)return`$${(n/1e9).toFixed(1)}B`;return`$${(n/1e6).toFixed(0)}M`}
const changeStyles={emerald:"bg-emerald-50 text-emerald-600",rose:"bg-rose-50 text-rose-600",orange:"bg-orange-50 text-orange-600",blue:"bg-blue-50 text-blue-600"} as const;

export default function HomeClient({coins,previousCoins=[],previousScannedAt,marketCoins=[],categories,updatedLabel}:Props){
 const[activeCategory,setActiveCategory]=useState("All coins");const[sort,setSort]=useState<SortOption>("signal-strength");const[scannerVisible,setScannerVisible]=useState(60);const[query,setQuery]=useState("");const[radarMode,setRadarMode]=useState<RadarMode>("heating");
 const eligible=useMemo(()=>coins.filter(c=>!isStablecoin(c.id,c.symbol)),[coins]);const trackedIds=useMemo(()=>new Set(eligible.map(c=>c.id)),[eligible]);const rankById=useMemo(()=>new Map(marketCoins.map(c=>[c.id,c.market_cap_rank]as const)),[marketCoins]);const discovery=useMemo(()=>sortCoins(activeCategory==="All coins"?eligible:eligible.filter(c=>c.category===activeCategory),sort),[eligible,activeCategory,sort]);const wider=useMemo(()=>marketCoins.filter(c=>!isStablecoin(c.id,c.symbol)&&!trackedIds.has(c.id)).sort((a,b)=>(a.market_cap_rank??99999)-(b.market_cap_rank??99999)),[marketCoins,trackedIds]);
 const oldMap=useMemo(()=>new Map(previousCoins.map(c=>[c.id,c]as const)),[previousCoins]);
 const transitionFor=(coin:Coin)=>{const old=oldMap.get(coin.id);if(!old)return null;const now=getSignalTier(coin),before=getSignalTier(old),delta=LEVEL[now]-LEVEL[before];return{now,before,delta,confidenceDelta:coin.confidencePct-old.confidencePct}};
 const changes=useMemo(()=>{if(!previousCoins.length)return null;const rows=eligible.flatMap(current=>{const old=oldMap.get(current.id);if(!old)return[];const now=getSignalTier(current),before=getSignalTier(old);return[{current,now,before,delta:LEVEL[now]-LEVEL[before],confidenceDelta:current.confidencePct-old.confidencePct}]});return{awakening:rows.filter(r=>r.now==="awakening"&&r.before!=="awakening"),volatile:rows.filter(r=>r.now==="volatile"&&r.before!=="volatile"),heated:rows.filter(r=>r.delta>0),cooled:rows.filter(r=>r.delta<0),compared:rows.length}},[eligible,previousCoins,oldMap]);
 const radar=useMemo(()=>{const fresh=(a:Coin,b:Coin)=>a.streakDays-b.streakDays||b.confidencePct-a.confidencePct;if(radarMode==="heating")return eligible.filter(c=>["awakening","volatile"].includes(getSignalTier(c))).sort(fresh).slice(0,5);if(radarMode==="cooling")return eligible.filter(c=>["building","calm"].includes(getSignalTier(c))).sort(fresh).slice(0,5);if(radarMode==="flipped")return eligible.filter(c=>c.streakDays<=2).sort(fresh).slice(0,5);return[...eligible].sort((a,b)=>getSparkScore(b).score-getSparkScore(a).score).slice(0,5)},[eligible,radarMode]);
 const results=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return[];const tracked=eligible.map(c=>({id:c.id,name:c.name,symbol:c.symbol,image:c.logoUrl||"",rank:rankById.get(c.id)??null,tracked:true}));const broad=wider.map(c=>({id:c.id,name:c.name,symbol:c.symbol,image:c.image,rank:c.market_cap_rank,tracked:false}));return[...tracked,...broad].filter(c=>c.name.toLowerCase().includes(q)||c.symbol.toLowerCase().includes(q)||c.id.toLowerCase().includes(q)).sort((a,b)=>Number(!(a.symbol.toLowerCase()===q||a.name.toLowerCase()===q))-Number(!(b.symbol.toLowerCase()===q||b.name.toLowerCase()===q))||(a.rank??99999)-(b.rank??99999)).slice(0,8)},[query,eligible,wider,rankById]);
 const coverage=useMemo(()=>{const cap=marketCoins.reduce((s,c)=>s+(c.market_cap??0),0);const btc=marketCoins.find(c=>c.id==="bitcoin")?.market_cap??0;const eth=marketCoins.find(c=>c.id==="ethereum")?.market_cap??0;const stable=marketCoins.filter(c=>isStablecoin(c.id,c.symbol)).reduce((s,c)=>s+(c.market_cap??0),0);const moves=marketCoins.map(c=>Math.abs(c.price_change_percentage_24h??0));return{cap,btcShare:cap?btc/cap*100:0,ethShare:cap?eth/cap*100:0,stableShare:cap?stable/cap*100:0,avgMove:moves.length?moves.reduce((a,b)=>a+b,0)/moves.length:0}},[marketCoins]);
 const cards=changes?[["Entered Awakening",changes.awakening.length,"↑","emerald"],["Entered Volatile",changes.volatile.length,"↘","rose"],["Heated Up",changes.heated.length,"↗","orange"],["Cooled Down",changes.cooled.length,"↓","blue"]] as const:[];
 return <main className="mx-auto max-w-[1390px] space-y-3 px-3 pb-3 pt-3 sm:px-5">
   <section className="grid grid-cols-2 gap-0 overflow-hidden rounded-[14px] border border-slate-200/70 bg-white/82 shadow-[0_4px_16px_rgba(20,35,75,.025)] sm:grid-cols-3 lg:grid-cols-5">
    {[["Coverage",`${marketCoins.length||eligible.length} assets`],["Covered market cap",coverage.cap?formatCompact(coverage.cap):"—"],["BTC share",coverage.btcShare?coverage.btcShare.toFixed(1)+"%":"—"],["Average 24h move",coverage.avgMove?coverage.avgMove.toFixed(1)+"%":"—"],["Data status",updatedLabel?`Updated ${updatedLabel}`:"Latest snapshot"]].map(([label,value],i)=><div key={label} className={`px-3 py-3 text-center ${i?"border-l border-slate-100":""}`}><p className="text-[9px] font-bold uppercase tracking-[.08em] text-slate-400">{label}</p><p className={`mt-1 text-[14px] font-bold sm:text-[15px] ${label==="Data status"?"text-emerald-700":"text-slate-900"}`}>{label==="Data status"&&"● "}{value}</p></div>)}
   </section>
   <section id="market-search" className="relative z-20 mx-auto max-w-2xl"><div className="relative"><span className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-sm text-slate-400">⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search coins (200+)" className="w-full rounded-xl border border-slate-200 bg-white py-3 pl-10 pr-10 text-[12px] shadow-sm outline-none focus:border-blue-300 focus:ring-2 focus:ring-blue-100"/>{query&&<button onClick={()=>setQuery("")} className="absolute right-3 top-1/2 -translate-y-1/2 text-[10px] text-slate-400">✕</button>}</div>{query&&<div className="absolute left-0 right-0 mt-1.5 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-xl">{results.length?results.map(c=><Link key={c.id} href={`/coin/${c.id}`} className="flex items-center gap-2.5 border-b border-slate-100 px-3 py-2.5 last:border-0 hover:bg-slate-50">{c.image?<img src={c.image} alt="" className="h-6 w-6 rounded-full"/>:<span className="h-6 w-6 rounded-full bg-slate-100"/>}<div className="min-w-0 flex-1"><p className="truncate text-[11px] font-semibold">{c.name}</p><p className="text-[8px] uppercase tracking-wider text-slate-400">{c.symbol}{c.rank?` · #${c.rank}`:""}</p></div><span className="text-[8px] font-semibold text-slate-400">{c.tracked?"Signal":"Analyse"}</span></Link>):<p className="p-4 text-center text-[10px] text-slate-400">No match in current coverage.</p>}</div>}</section>
   <section className="rounded-[16px] border border-slate-200/70 bg-white/84 p-4 shadow-[0_6px_20px_rgba(20,35,75,.03)]"><div className="flex items-center justify-between gap-3"><CompactTitle title="What changed today?"/><span className="text-[10px] font-medium text-slate-400">{previousScannedAt?`vs ${new Date(previousScannedAt).toLocaleDateString()}`:"Waiting for next saved scan"}</span></div>{changes?<div className="mt-3 grid grid-cols-2 gap-2 lg:grid-cols-4">{cards.map(([label,count,icon,color])=><div key={label} className="rounded-xl border border-slate-200/70 bg-white px-3 py-3"><div className="flex items-center gap-3"><span className={`flex h-9 w-9 items-center justify-center rounded-full text-lg ${changeStyles[color]}`}>{icon}</span><div><p className="text-[11px] font-semibold text-slate-900">{label}</p><p className="text-[10px] text-slate-500">{count} coins</p></div></div></div>)}</div>:<p className="mt-3 rounded-xl bg-slate-50 p-5 text-center text-[10px] text-slate-400">Waiting for the next saved scan.</p>}</section>
   <div className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_290px]">
    <div className="space-y-3">
     <section className="rounded-[16px] border border-slate-200/70 bg-white/84 p-4 shadow-[0_6px_20px_rgba(20,35,75,.03)]"><div className="flex flex-wrap items-center justify-between gap-2"><CompactTitle title="Spark Radar"/><div className="flex flex-wrap justify-end gap-1.5">{([['heating','🔥 Heating Up'],['cooling','❄ Cooling Down'],['flipped','↻ Just Flipped'],['strongest','⚡ Strongest Signals']]as[RadarMode,string][]).map(([m,l])=><button key={m} onClick={()=>setRadarMode(m)} className={`rounded-full px-3 py-1.5 text-[9px] font-semibold ${radarMode===m?'bg-slate-950 text-white':'border border-slate-200 bg-white text-slate-500'}`}>{l}</button>)}</div></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-5">{radar.map(c=><ScannerCard key={c.id} coin={c}/>)}</div></section>
     <section className="rounded-[16px] border border-slate-200/70 bg-white/86 p-4 shadow-[0_6px_20px_rgba(20,35,75,.03)]"><div className="flex flex-wrap items-center justify-between gap-2"><CompactTitle title="Top 30 Discovery"/><div className="flex items-center justify-end gap-2"><FilterPills categories={categories} active={activeCategory} onChange={setActiveCategory}/><SortControl value={sort} onChange={setSort}/></div></div>
      <div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3 md:hidden">{discovery.map(c=><ScannerCard key={c.id} coin={c}/>)}</div>
      <div className="mt-3 hidden overflow-x-auto md:block"><table className="w-full min-w-[900px] border-collapse text-left"><thead><tr className="border-b border-slate-200 text-[8px] uppercase tracking-wider text-slate-400"><th className="px-2 py-2">#</th><th className="px-2 py-2">Coin</th><th className="px-2 py-2 text-center">Price</th><th className="px-2 py-2 text-center">24h</th><th className="px-2 py-2 text-center">Regime</th><th className="px-2 py-2 text-center">Confidence</th><th className="px-2 py-2 text-center">SparkScore</th><th className="px-2 py-2 text-center">Change today</th><th className="px-2 py-2 text-center">Actions</th></tr></thead><tbody>{discovery.map((c,i)=>{const tier=getSignalTier(c),cfg=TIER_CONFIG[tier],spark=getSparkScore(c),tr=transitionFor(c);const change=tr?(tr.delta>0?`↑ ${tr.before} → ${tr.now}`:tr.delta<0?`↓ ${tr.before} → ${tr.now}`:Math.abs(tr.confidenceDelta)>=1?`${tr.confidenceDelta>0?'+':''}${tr.confidenceDelta.toFixed(0)} confidence`:'No change'):'—';return <tr key={c.id} className="border-b border-slate-100 text-[10px] last:border-0 hover:bg-slate-50/70"><td className="px-2 py-2.5 text-slate-400">{i+1}</td><td className="px-2 py-2.5"><div className="flex items-center gap-2"><WatchlistButton coinId={c.id} compact/>{c.logoUrl?<img src={c.logoUrl} alt="" className="h-6 w-6 rounded-full"/>:<span className="h-6 w-6 rounded-full bg-slate-100"/>}<Link href={`/coin/${c.id}`} className="font-semibold text-slate-900">{c.symbol}</Link><span className="text-slate-400">{c.name}</span></div></td><td className="px-2 py-2.5 text-center font-semibold"><CurrencyAmount usd={c.price}/></td><td className={`px-2 py-2.5 text-center font-semibold ${c.change24hPct>=0?'text-emerald-600':'text-rose-600'}`}>{c.change24hPct>=0?'+':''}{c.change24hPct.toFixed(1)}%</td><td className="px-2 py-2.5 text-center"><span className={`rounded-full px-2 py-1 text-[8px] font-semibold ${cfg.bg} ${cfg.text}`}>{cfg.label}</span></td><td className="px-2 py-2.5 text-center font-medium">{c.confidencePct.toFixed(0)}%</td><td className="px-2 py-2.5"><div className="flex items-center justify-center gap-2"><div className="h-1.5 w-14 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-pink-500 to-orange-400" style={{width:`${spark.score}%`}}/></div><span className="rounded-full bg-rose-50 px-2 py-1 text-[8px] font-bold text-rose-600">{spark.score}</span></div></td><td className={`px-2 py-2.5 text-center text-[9px] font-medium ${tr?.delta&&tr.delta>0?'text-emerald-600':tr?.delta&&tr.delta<0?'text-blue-600':'text-slate-400'}`}>{change}</td><td className="px-2 py-2.5"><div className="flex items-center justify-center gap-1"><Link href={`/coin/${c.id}`} className="rounded-full border border-slate-200 px-2 py-1 text-[8px] font-semibold text-slate-600">Why?</Link><AlertRuleButton coinId={c.id} compact/></div></td></tr>})}</tbody></table></div>
     </section>
    </div>
    <aside className="space-y-3">
      <section className="rounded-[16px] border border-slate-200/70 bg-white/86 p-4 shadow-[0_6px_20px_rgba(20,35,75,.03)]"><div className="flex items-center justify-between"><CompactTitle title="Beyond the tracker"/><span className="text-[10px] text-slate-400">Top wider assets</span></div><div className="mt-3 divide-y divide-slate-100">{wider.slice(0,6).map(c=><Link href={`/coin/${c.id}`} key={c.id} className="flex items-center gap-2 py-2.5 hover:bg-slate-50"><img src={c.image} alt="" className="h-6 w-6 rounded-full object-contain"/><div className="min-w-0 flex-1"><p className="truncate text-[10px] font-semibold text-slate-900">{c.name}</p><p className="text-[8px] uppercase text-slate-400">{c.symbol} {c.market_cap_rank?`· #${c.market_cap_rank}`:""}</p></div><div className="text-right"><p className="text-[10px] font-semibold text-slate-800"><CurrencyAmount usd={c.current_price}/></p><p className={`text-[8px] font-semibold ${(c.price_change_percentage_24h??0)>=0?'text-emerald-600':'text-rose-600'}`}>{(c.price_change_percentage_24h??0)>=0?'+':''}{(c.price_change_percentage_24h??0).toFixed(1)}%</p></div></Link>)}</div></section>
      <section className="rounded-[16px] border border-slate-200/70 bg-white/86 p-4 shadow-[0_6px_20px_rgba(20,35,75,.03)]"><CompactTitle title="Coverage"/><div className="mt-3 divide-y divide-slate-100 text-[10px]">{[["Assets tracked",`${marketCoins.length||eligible.length}+`],["Covered market cap",coverage.cap?formatCompact(coverage.cap):"—"],["BTC share",coverage.btcShare?coverage.btcShare.toFixed(1)+"%":"—"],["ETH share",coverage.ethShare?coverage.ethShare.toFixed(1)+"%":"—"],["Stablecoin share",coverage.stableShare?coverage.stableShare.toFixed(1)+"%":"—"]].map(([l,v])=><div key={l} className="flex items-center justify-between gap-3 py-2"><span className="font-medium text-slate-500">{l}</span><strong className="text-slate-900">{v}</strong></div>)}</div></section>
    </aside>
   </div>
   {wider.length>0&&<section className="rounded-[16px] border border-slate-200/70 bg-white/80 p-4"><div className="flex items-center justify-between"><CompactTitle title="Wider Market"/><span className="text-[10px] font-medium text-slate-400">Beyond the tracked leaders</span></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6">{wider.slice(0,scannerVisible).map(c=><MarketBreadthCard key={c.id} coin={c}/>)}</div>{scannerVisible<wider.length&&<div className="mt-4 text-center"><button onClick={()=>setScannerVisible(v=>v+60)} className="rounded-full border border-slate-200 bg-white px-4 py-2 text-[10px] font-semibold text-slate-600">Load 60 more</button></div>}</section>}
 </main>;
}
