"use client";

import { FormEvent, ReactNode, useEffect, useMemo, useRef, useState } from "react";
import type { RealtimeChannel } from "@supabase/supabase-js";
import { getSupabaseBrowserClient } from "@/lib/supabaseClient";
import type { CoinMeta } from "@/lib/coingecko";

type ChatMessage={id:string;user_id:string;display_name:string;body:string;coin_symbol:string|null;created_at:string};
type Period="24H"|"7D";type MarketFilter="All"|"Top"|"Privacy";type MobileTab="Market"|"Chat";type Tick="up"|"down";
const privacy=new Set(["xmr","zec","firo","dash","scrt","rose","arrr"]);
function money(n:number){if(n>=1000)return `$${n.toLocaleString(undefined,{maximumFractionDigits:0})}`;if(n>=1)return `$${n.toLocaleString(undefined,{maximumFractionDigits:4})}`;return `$${n.toLocaleString(undefined,{maximumSignificantDigits:4})}`}
function initials(n:string){return n.trim().slice(0,2).toUpperCase()||"CS"}
function appendUnique(a:ChatMessage[],m:ChatMessage){return a.some(x=>x.id===m.id)?a:[...a.slice(-79),m]}
function changeFor(c:CoinMeta,p:Period){return p==="7D"?(c.price_change_percentage_7d_in_currency??c.price_change_percentage_24h??0):(c.price_change_percentage_24h??0)}

export default function LiveMarketRoom({coins}:{coins:CoinMeta[]}){
 const[marketCoins,setMarketCoins]=useState(coins),[period,setPeriod]=useState<Period>("24H"),[marketFilter,setMarketFilter]=useState<MarketFilter>("All"),[mobileTab,setMobileTab]=useState<MobileTab>("Market"),[selected,setSelected]=useState<string|null>(null),[messages,setMessages]=useState<ChatMessage[]>([]),[body,setBody]=useState(""),[userId,setUserId]=useState<string|null>(null),[displayName,setDisplayName]=useState("Guest"),[chatReady,setChatReady]=useState(false),[chatLoadError,setChatLoadError]=useState(false),[sendError,setSendError]=useState<string|null>(null),[sending,setSending]=useState(false),[enteringIds,setEnteringIds]=useState<Set<string>>(new Set()),[ticks,setTicks]=useState<Record<string,Tick>>({});
 const endRef=useRef<HTMLDivElement|null>(null),rowRefs=useRef<Record<string,HTMLButtonElement|null>>({}),coinsRef=useRef(marketCoins);
 useEffect(()=>{coinsRef.current=marketCoins},[marketCoins]);
 const filtered=useMemo(()=>{let r=marketCoins.slice(0,48);if(marketFilter==="Top")r=r.slice(0,20);if(marketFilter==="Privacy")r=r.filter(c=>privacy.has(c.symbol.toLowerCase()));return r},[marketCoins,marketFilter]);
 const average=filtered.length?filtered.reduce((s,c)=>s+changeFor(c,period),0)/filtered.length:0;
 const movers=useMemo(()=>[...filtered].sort((a,b)=>Math.abs(changeFor(b,period))-Math.abs(changeFor(a,period))).slice(0,8),[filtered,period]);
 const selectedCoin=marketCoins.find(c=>c.symbol.toLowerCase()===selected)||null;
 function selectCoin(symbol:string,fromChat=false){const s=symbol.toLowerCase();setSelected(s);if(fromChat){setMobileTab("Market");setTimeout(()=>rowRefs.current[s]?.scrollIntoView({behavior:"smooth",block:"center"}),80)}}
 function renderBody(text:string):ReactNode[]{return text.split(/(\$[A-Za-z0-9]{2,10})/g).map((p,i)=>/^\$[A-Za-z0-9]{2,10}$/.test(p)?<button key={i} type="button" onClick={()=>selectCoin(p.slice(1),true)} className="font-black underline decoration-current/30 underline-offset-2">{p.toUpperCase()}</button>:<span key={i}>{p}</span>)}
 function animateMessage(id:string){setEnteringIds(s=>new Set(s).add(id));setTimeout(()=>setEnteringIds(s=>{const n=new Set(s);n.delete(id);return n}),30)}
 useEffect(()=>{let active=true;async function refresh(){try{const response=await fetch("/api/live-market",{cache:"no-store"});if(!response.ok)return;const json=await response.json();if(!active||!Array.isArray(json.coins))return;const previous=new Map(coinsRef.current.map(c=>[c.id,c.current_price]));const nextTicks:Record<string,Tick>={};for(const c of json.coins as CoinMeta[]){const old=previous.get(c.id);if(typeof old==="number"&&c.current_price!==old)nextTicks[c.symbol.toLowerCase()]=c.current_price>old?"up":"down"}setTicks(nextTicks);setMarketCoins(json.coins);if(Object.keys(nextTicks).length)setTimeout(()=>active&&setTicks({}),380)}catch{}}void refresh();const timer=setInterval(refresh,30000);return()=>{active=false;clearInterval(timer)}},[]);
 useEffect(()=>{let mounted=true;let channel:RealtimeChannel|null=null;const supabase=getSupabaseBrowserClient();async function boot(){const{data:auth}=await supabase.auth.getUser();if(!mounted)return;if(auth.user){setUserId(auth.user.id);const meta=auth.user.user_metadata||{};setDisplayName(String(meta.display_name||meta.full_name||auth.user.email?.split("@")[0]||"Member"))}const{data,error}=await supabase.from("community_messages").select("id,user_id,display_name,body,coin_symbol,created_at").order("created_at",{ascending:true}).limit(80);if(!mounted)return;if(error){setChatLoadError(true);setChatReady(true);return}setMessages((data||[]) as ChatMessage[]);setChatReady(true);channel=supabase.channel("coinspark-live-chat").on("postgres_changes",{event:"INSERT",schema:"public",table:"community_messages"},payload=>{const m=payload.new as ChatMessage;setMessages(a=>appendUnique(a,m));animateMessage(m.id)}).subscribe()}void boot();return()=>{mounted=false;if(channel)void supabase.removeChannel(channel)}},[]);
 useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth",block:"nearest"})},[messages.length]);
 async function sendMessage(e:FormEvent){e.preventDefault();const text=body.trim();if(!text||!userId||sending)return;setSending(true);setSendError(null);const symbol=text.match(/\$([A-Za-z0-9]{2,10})/)?.[1]?.toUpperCase()||selected?.toUpperCase()||null;const table=getSupabaseBrowserClient().from("community_messages") as any;const{data,error}=await table.insert({user_id:userId,display_name:displayName.slice(0,40),body:text.slice(0,500),coin_symbol:symbol}).select("id,user_id,display_name,body,coin_symbol,created_at").single();if(error)setSendError("Message could not be sent. Please try again.");else{if(data){setMessages(a=>appendUnique(a,data as ChatMessage));animateMessage(data.id)}setBody("")}setSending(false)}
 return <div>
  <div className="mb-4 grid grid-cols-2 gap-2 rounded-[var(--csl-radius-lg)] border bg-[var(--csl-surface)] p-1.5 shadow-[var(--csl-shadow-xs)] lg:hidden">{(["Market","Chat"] as MobileTab[]).map(t=><button key={t} onClick={()=>setMobileTab(t)} className={`rounded-[var(--csl-radius-md)] px-4 py-2.5 text-xs font-bold ${mobileTab===t?"bg-[var(--csl-ink)] text-white":"text-[var(--csl-ink-muted)]"}`}>{t}</button>)}</div>
  <div className="grid items-start gap-[var(--csl-stack-space)] lg:grid-cols-[minmax(0,1.65fr)_minmax(20rem,1fr)]">
   <section className={`${mobileTab==="Chat"?"hidden lg:block":"block"} overflow-hidden rounded-[var(--csl-radius-xl)] border bg-[var(--csl-surface)] shadow-[var(--csl-shadow-sm)]`}>
    <header className="border-b px-5 py-5 sm:px-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[var(--brand-blue)]">Live market universe</p><h2 className="mt-1">Market pulse</h2><p className="mt-2 text-xs text-[var(--csl-ink-subtle)]">{filtered.length} assets visible · Average move <b key={`${period}-${average.toFixed(3)}`} className={`${average>=0?"text-[var(--regime-calm)]":"text-[var(--regime-volatile)]"} inline-block animate-pulse`}>{average>=0?"+":""}{average.toFixed(2)}%</b></p></div><div className="flex flex-wrap gap-2">{(["All","Top","Privacy"] as MarketFilter[]).map(x=><button key={x} onClick={()=>setMarketFilter(x)} className={`rounded-full border px-3.5 py-2 text-[10px] font-bold ${marketFilter===x?"bg-[var(--csl-ink)] text-white":"bg-[var(--csl-surface-solid)] text-[var(--csl-ink-muted)]"}`}>{x}</button>)}{(["24H","7D"] as Period[]).map(x=><button key={x} onClick={()=>setPeriod(x)} className={`rounded-full border px-3.5 py-2 text-[10px] font-bold ${period===x?"bg-[var(--brand-blue)] text-white":"bg-[var(--csl-surface-solid)] text-[var(--brand-blue)]"}`}>{x}</button>)}</div></div></header>
    <div className="border-b p-4 sm:p-5"><div className="mb-3 flex items-center justify-between"><h3 className="text-base">Top movers</h3><span className="text-[10px] font-bold text-[var(--csl-ink-subtle)]">{period}</span></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{movers.map(c=>{const move=changeFor(c,period),up=move>=0;return <button key={c.id} onClick={()=>selectCoin(c.symbol)} className={`rounded-[var(--csl-radius-md)] border bg-[var(--csl-surface-solid)] p-3 text-left shadow-[var(--csl-shadow-xs)] ${selected===c.symbol.toLowerCase()?"ring-2 ring-[var(--brand-blue)]":""}`}><div className="flex items-center gap-2"><img src={c.image} alt="" className="h-6 w-6 rounded-full"/><b className="text-xs">{c.symbol.toUpperCase()}</b></div><div className="mt-2 flex items-end justify-between gap-2"><span className="text-xs font-bold">{money(c.current_price)}</span><span className={`text-[10px] font-black ${up?"text-[var(--regime-calm)]":"text-[var(--regime-volatile)]"}`}>{up?"+":""}{move.toFixed(2)}%</span></div></button>})}</div></div>
    <div className="max-h-[650px] overflow-auto"><div className="sticky top-0 z-10 grid grid-cols-[minmax(0,1.4fr)_1fr_.7fr] border-b bg-[var(--csl-surface-solid)] px-5 py-3 text-[10px] font-bold uppercase tracking-[.08em] text-[var(--csl-ink-subtle)] sm:px-6"><span>Asset</span><span className="text-right">Price</span><span className="text-right">{period}</span></div>{filtered.map(c=>{const move=changeFor(c,period),up=move>=0,active=selected===c.symbol.toLowerCase(),tick=ticks[c.symbol.toLowerCase()];return <button ref={el=>{rowRefs.current[c.symbol.toLowerCase()]=el}} key={c.id} onClick={()=>selectCoin(c.symbol)} style={{transition:`background-color var(--csl-duration-slow) var(--csl-ease), box-shadow var(--csl-duration-fast) var(--csl-ease)`}} className={`grid w-full grid-cols-[minmax(0,1.4fr)_1fr_.7fr] items-center border-b border-l-[3px] px-5 py-3.5 text-left sm:px-6 ${up?"border-l-[var(--regime-calm)]":"border-l-[var(--regime-volatile)]"} ${tick==="up"?"bg-[var(--regime-calm-soft)]":tick==="down"?"bg-[var(--regime-volatile-soft)]":active?"bg-[var(--csl-surface-muted)] ring-1 ring-inset ring-[var(--brand-blue)]":"bg-transparent hover:bg-[var(--csl-surface-muted)]"}`}><span className="flex min-w-0 items-center gap-3"><img src={c.image} alt="" className="h-8 w-8 rounded-full"/><span className="min-w-0"><b className="block truncate text-sm">{c.name}</b><small className="text-[10px] font-bold text-[var(--csl-ink-subtle)]">{c.symbol.toUpperCase()}</small></span></span><b className="text-right text-xs">{money(c.current_price)}</b><b className={`text-right text-xs ${up?"text-[var(--regime-calm)]":"text-[var(--regime-volatile)]"}`}>{up?"+":""}{move.toFixed(2)}%</b></button>})}</div>
   </section>
   <aside className={`${mobileTab==="Market"?"hidden lg:flex":"flex"} h-[calc(100dvh-7rem)] min-h-[620px] flex-col overflow-hidden rounded-[var(--csl-radius-xl)] border bg-[var(--csl-surface)] shadow-[var(--csl-shadow-sm)] lg:sticky lg:top-[5.5rem]`}>
    <header className="border-b px-5 py-4"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[var(--brand-blue)]">CoinSpark Live</p><h2 className="mt-1 text-xl">Community chat</h2></div><span className="rounded-full bg-[var(--regime-calm-soft)] px-3 py-1.5 text-[9px] font-black text-[var(--regime-calm)]">REAL TIME</span></div><div className="mt-3 rounded-[var(--csl-radius-md)] border bg-[var(--csl-surface-muted)] px-3 py-2.5 text-xs font-bold text-[var(--csl-ink-muted)]">💬 {selectedCoin?<>Discussing <span className="text-[var(--csl-ink)]">${selectedCoin.symbol.toUpperCase()}</span> · {money(selectedCoin.current_price)}</>:"Global room · select a coin for context"}</div></header>
    <div className="flex-1 space-y-3 overflow-y-auto bg-[var(--csl-surface-muted)] p-4">{!chatReady&&<div className="rounded-[var(--csl-radius-md)] bg-white p-4 text-center text-xs font-bold text-[var(--csl-ink-subtle)]">Connecting to community…</div>}{chatReady&&chatLoadError&&<div className="rounded-[var(--csl-radius-md)] bg-[var(--regime-building-soft)] p-4 text-center text-xs font-bold text-[var(--regime-building)]">Community connection is temporarily unavailable.</div>}{chatReady&&!chatLoadError&&messages.length===0&&<div className="rounded-[var(--csl-radius-md)] border border-dashed bg-white p-6 text-center"><b>The room is open.</b><p className="mt-1 text-xs text-[var(--csl-ink-subtle)]">Be the first person to start the conversation.</p></div>}{messages.map(m=>{const mine=m.user_id===userId,entering=enteringIds.has(m.id);return <div key={m.id} className={`flex gap-2.5 ${mine?"flex-row-reverse":""} ${entering?"translate-y-2 opacity-0":"translate-y-0 opacity-100"}`} style={{transition:`opacity var(--csl-duration-slow) var(--csl-ease), transform var(--csl-duration-slow) var(--csl-ease)`}}><div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-[9px] font-black ${mine?"bg-[var(--brand-blue)] text-white":"bg-white text-[var(--csl-ink-muted)] shadow-[var(--csl-shadow-xs)]"}`}>{initials(m.display_name)}</div><div className={`max-w-[84%] rounded-[var(--csl-radius-lg)] px-3.5 py-2.5 shadow-[var(--csl-shadow-xs)] ${mine?"bg-[var(--brand-blue)] text-white":"bg-white text-[var(--csl-ink)]"}`}><div className="mb-1 text-[9px] font-bold opacity-75">{m.display_name}</div><p className="break-words text-xs leading-5">{renderBody(m.body)}</p></div></div>})}<div ref={endRef}/></div>
    <div className="border-t bg-[var(--csl-surface-solid)] p-4">{sendError&&<div className="mb-3 rounded-[var(--csl-radius-md)] bg-[var(--regime-building-soft)] px-3 py-2 text-[10px] font-bold text-[var(--regime-building)]">{sendError}</div>}{userId?<form onSubmit={sendMessage} className="flex items-end gap-2"><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={500} rows={2} placeholder={selected?`Message the global room about $${selected.toUpperCase()}…`:"Write a message…"} className="min-h-12 flex-1 resize-none rounded-[var(--csl-radius-lg)] border bg-[var(--csl-surface-muted)] px-3.5 py-3 text-xs outline-none"/><button disabled={!body.trim()||sending} className="csl-btn-primary h-12 px-4 disabled:opacity-40">{sending?"…":"Send"}</button></form>:<div className="text-center text-xs font-bold text-[var(--csl-ink-muted)]">Sign in to join the global conversation.</div>}<p className="mt-2 text-center text-[9px] text-[var(--csl-ink-subtle)]">Public room · no financial advice · report abuse rather than engaging.</p></div>
   </aside>
  </div>
 </div>
}
