"use client";

import {FormEvent,ReactNode,useEffect,useMemo,useRef,useState} from "react";
import type {RealtimeChannel} from "@supabase/supabase-js";
import {getSupabaseBrowserClient} from "@/lib/supabaseClient";
import type {CoinMeta} from "@/lib/coingecko";

type ChatMessage={id:string;user_id:string;display_name:string;body:string;coin_symbol:string|null;created_at:string};
type Period="24H"|"7D";type MarketFilter="All"|"Top"|"Privacy";type MobileTab="Market"|"Chat";type ConnectionState="connecting"|"live"|"degraded";
const privacy=new Set(["xmr","zec","firo","dash","scrt","rose","arrr"]);
function money(n:number){if(n>=1000)return `$${n.toLocaleString(undefined,{maximumFractionDigits:0})}`;if(n>=1)return `$${n.toLocaleString(undefined,{maximumFractionDigits:4})}`;return `$${n.toLocaleString(undefined,{maximumSignificantDigits:4})}`}
function changeFor(c:CoinMeta,p:Period){return p==="7D"?(c.price_change_percentage_7d_in_currency??c.price_change_percentage_24h??0):(c.price_change_percentage_24h??0)}
function appendUnique(a:ChatMessage[],m:ChatMessage){return a.some(x=>x.id===m.id)?a:[...a.slice(-79),m]}
function initials(n:string){return n.trim().slice(0,2).toUpperCase()||"CS"}
function timeLabel(value:number|null){if(!value)return"Not refreshed yet";const seconds=Math.max(0,Math.round((Date.now()-value)/1000));return seconds<10?"Updated just now":seconds<60?`Updated ${seconds}s ago`:`Updated ${Math.floor(seconds/60)}m ago`}

export default function LiveMarketRoom({coins}:{coins:CoinMeta[]}){
 const[marketCoins,setMarketCoins]=useState(coins),[period,setPeriod]=useState<Period>("24H"),[marketFilter,setMarketFilter]=useState<MarketFilter>("All"),[mobileTab,setMobileTab]=useState<MobileTab>("Market"),[selected,setSelected]=useState<string|null>(coins[0]?.symbol?.toLowerCase()||null),[messages,setMessages]=useState<ChatMessage[]>([]),[body,setBody]=useState(""),[userId,setUserId]=useState<string|null>(null),[displayName,setDisplayName]=useState("Guest"),[chatReady,setChatReady]=useState(false),[chatLoadError,setChatLoadError]=useState(false),[chatState,setChatState]=useState<ConnectionState>("connecting"),[marketState,setMarketState]=useState<ConnectionState>("connecting"),[lastMarketUpdate,setLastMarketUpdate]=useState<number|null>(null),[sendError,setSendError]=useState<string|null>(null),[sending,setSending]=useState(false),[retryKey,setRetryKey]=useState(0);
 const endRef=useRef<HTMLDivElement|null>(null),rowRefs=useRef<Record<string,HTMLButtonElement|null>>({}),coinsRef=useRef(marketCoins);
 useEffect(()=>{coinsRef.current=marketCoins},[marketCoins]);
 const filtered=useMemo(()=>{let r=marketCoins.slice(0,48);if(marketFilter==="Top")r=r.slice(0,20);if(marketFilter==="Privacy")r=r.filter(c=>privacy.has(c.symbol.toLowerCase()));return r},[marketCoins,marketFilter]);
 const movers=useMemo(()=>[...filtered].sort((a,b)=>Math.abs(changeFor(b,period))-Math.abs(changeFor(a,period))).slice(0,6),[filtered,period]);
 const average=filtered.length?filtered.reduce((s,c)=>s+changeFor(c,period),0)/filtered.length:0;
 const selectedCoin=marketCoins.find(c=>c.symbol.toLowerCase()===selected)||null;
 function selectCoin(symbol:string,fromChat=false){const s=symbol.toLowerCase();setSelected(s);if(fromChat){setMobileTab("Market");setTimeout(()=>rowRefs.current[s]?.scrollIntoView({behavior:"smooth",block:"center"}),80)}}
 function renderBody(text:string):ReactNode[]{return text.split(/(\$[A-Za-z0-9]{2,10})/g).map((part,i)=>/^\$[A-Za-z0-9]{2,10}$/.test(part)?<button key={i} type="button" onClick={()=>selectCoin(part.slice(1),true)} className="cs-live-tag">{part.toUpperCase()}</button>:<span key={i}>{part}</span>)}
 useEffect(()=>{let active=true;async function refresh(){setMarketState(s=>s==="live"?"live":"connecting");try{const r=await fetch("/api/live-market",{cache:"no-store"});if(!r.ok)throw new Error("market unavailable");const json=await r.json();if(!active||!Array.isArray(json.coins))return;setMarketCoins(json.coins);setLastMarketUpdate(Date.now());setMarketState("live")}catch{if(active)setMarketState("degraded")}}void refresh();const timer=setInterval(refresh,30000);return()=>{active=false;clearInterval(timer)}},[]);
 useEffect(()=>{let mounted=true;let channel:RealtimeChannel|null=null;const supabase=getSupabaseBrowserClient();setChatReady(false);setChatLoadError(false);setChatState("connecting");async function boot(){const{data:auth}=await supabase.auth.getUser();if(!mounted)return;if(auth.user){setUserId(auth.user.id);const meta=auth.user.user_metadata||{};setDisplayName(String(meta.display_name||meta.full_name||auth.user.email?.split("@")[0]||"Member"))}else setUserId(null);const{data,error}=await supabase.from("community_messages").select("id,user_id,display_name,body,coin_symbol,created_at").order("created_at",{ascending:true}).limit(80);if(!mounted)return;if(error){setChatLoadError(true);setChatReady(true);setChatState("degraded");return}setMessages((data||[]) as ChatMessage[]);setChatReady(true);channel=supabase.channel("coinspark-live-chat").on("postgres_changes",{event:"INSERT",schema:"public",table:"community_messages"},payload=>setMessages(a=>appendUnique(a,payload.new as ChatMessage))).subscribe(status=>{if(!mounted)return;if(status==="SUBSCRIBED")setChatState("live");else if(status==="CHANNEL_ERROR"||status==="TIMED_OUT"||status==="CLOSED")setChatState("degraded");else setChatState("connecting")})}void boot();return()=>{mounted=false;if(channel)void supabase.removeChannel(channel)}},[retryKey]);
 useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth",block:"nearest"})},[messages.length]);
 async function sendMessage(e:FormEvent){e.preventDefault();const text=body.trim();if(!text||!userId||sending)return;setSending(true);setSendError(null);const symbol=text.match(/\$([A-Za-z0-9]{2,10})/)?.[1]?.toUpperCase()||selected?.toUpperCase()||null;const table=getSupabaseBrowserClient().from("community_messages") as any;const{data,error}=await table.insert({user_id:userId,display_name:displayName.slice(0,40),body:text.slice(0,500),coin_symbol:symbol}).select("id,user_id,display_name,body,coin_symbol,created_at").single();if(error)setSendError(error.message.includes("rate")?"You are posting too quickly. Try again shortly.":"Message could not be sent. Please try again.");else{if(data)setMessages(a=>appendUnique(a,data as ChatMessage));setBody("")}setSending(false)}
 const chatLabel=chatState==="live"?"Realtime connected":chatState==="connecting"?"Connecting…":"Connection degraded";
 const marketLabel=marketState==="live"?timeLabel(lastMarketUpdate):marketState==="connecting"?"Refreshing market…":"Market refresh delayed";
 return <div className="cs-live-room">
  <div className="cs-live-context" aria-live="polite"><div><span className="cs-live-context__eyebrow">Selected market</span>{selectedCoin?<><strong>${selectedCoin.symbol.toUpperCase()} · {selectedCoin.name}</strong><small>{money(selectedCoin.current_price)} · {changeFor(selectedCoin,period)>=0?"+":""}{changeFor(selectedCoin,period).toFixed(2)}% {period}</small></>:<><strong>Global market</strong><small>Select an asset to focus the room.</small></>}</div><div className="cs-live-context__states"><span data-state={marketState}>{marketLabel}</span><span data-state={chatState}>{chatLabel}</span></div></div>
  <div className="cs-live-mobile-tabs" role="tablist" aria-label="CoinSpark Live views">{(["Market","Chat"] as MobileTab[]).map(tab=><button key={tab} role="tab" aria-selected={mobileTab===tab} onClick={()=>setMobileTab(tab)}>{tab}</button>)}</div>
  <div className="cs-live-grid">
   <section className={`cs-live-market ${mobileTab==="Chat"?"cs-live-mobile-hidden":""}`} aria-label="Live market">
    <header className="cs-live-panel-head"><div><p className="cs-eyebrow">Market pulse</p><h2>What is moving now?</h2><p>{filtered.length} assets · average {period} move <b data-direction={average>=0?"up":"down"}>{average>=0?"+":""}{average.toFixed(2)}%</b></p></div><div className="cs-live-filters">{(["All","Top","Privacy"] as MarketFilter[]).map(x=><button key={x} data-active={marketFilter===x} onClick={()=>setMarketFilter(x)}>{x}</button>)}{(["24H","7D"] as Period[]).map(x=><button key={x} data-active={period===x} onClick={()=>setPeriod(x)}>{x}</button>)}</div></header>
    {marketState==="degraded"&&<div className="cs-live-warning" role="status"><strong>Market updates are delayed.</strong><span>The last successful values remain visible while CoinSparkLine retries automatically.</span></div>}
    <div className="cs-live-movers"><div className="cs-live-section-label"><strong>Largest moves</strong><span>{period}</span></div><div className="cs-live-mover-grid">{movers.map(c=>{const move=changeFor(c,period);return <button key={c.id} data-active={selected===c.symbol.toLowerCase()} onClick={()=>selectCoin(c.symbol)}><span><img src={c.image} alt=""/><b>{c.symbol.toUpperCase()}</b></span><strong>{money(c.current_price)}</strong><small data-direction={move>=0?"up":"down"}>{move>=0?"+":""}{move.toFixed(2)}%</small></button>})}</div></div>
    <div className="cs-live-table"><div className="cs-live-table__head"><span>Asset</span><span>Price</span><span>{period}</span></div>{filtered.map(c=>{const move=changeFor(c,period),active=selected===c.symbol.toLowerCase();return <button ref={el=>{rowRefs.current[c.symbol.toLowerCase()]=el}} key={c.id} data-active={active} onClick={()=>selectCoin(c.symbol)}><span className="cs-live-asset"><img src={c.image} alt=""/><span><b>{c.name}</b><small>{c.symbol.toUpperCase()}</small></span></span><strong>{money(c.current_price)}</strong><strong data-direction={move>=0?"up":"down"}>{move>=0?"+":""}{move.toFixed(2)}%</strong></button>})}</div>
   </section>
   <aside className={`cs-live-chat ${mobileTab==="Market"?"cs-live-mobile-hidden":""}`} aria-label="Community chat">
    <header className="cs-live-panel-head cs-live-chat-head"><div><p className="cs-eyebrow">Community</p><h2>CoinSpark Live</h2><p>{selectedCoin?<>Discussing <b>${selectedCoin.symbol.toUpperCase()}</b></>:"Global room"}</p></div><span className="cs-live-state-pill" data-state={chatState}>{chatLabel}</span></header>
    <div className="cs-live-messages">{!chatReady&&<div className="cs-live-empty" role="status">Connecting to community…</div>}{chatReady&&chatLoadError&&<div className="cs-live-empty"><strong>Community connection is unavailable.</strong><button type="button" onClick={()=>setRetryKey(x=>x+1)}>Reconnect</button></div>}{chatReady&&!chatLoadError&&messages.length===0&&<div className="cs-live-empty"><strong>The room is open.</strong><span>Be the first to start the conversation.</span></div>}{messages.map(m=>{const mine=m.user_id===userId;return <article key={m.id} className="cs-live-message" data-mine={mine}><div className="cs-live-avatar">{initials(m.display_name)}</div><div><small>{m.display_name}</small><p>{renderBody(m.body)}</p>{m.coin_symbol&&<button type="button" className="cs-live-message-context" onClick={()=>selectCoin(m.coin_symbol!,true)}>${m.coin_symbol}</button>}</div></article>})}<div ref={endRef}/></div>
    <form className="cs-live-composer" onSubmit={sendMessage}>{userId?<><label htmlFor="live-message">Message</label><textarea id="live-message" value={body} onChange={e=>setBody(e.target.value)} maxLength={500} rows={3} placeholder={selectedCoin?`Discuss $${selectedCoin.symbol.toUpperCase()}…":"Write a message…"}/><div className="cs-live-composer__foot"><span>{body.length}/500 · use $TICKER to link an asset</span><button type="submit" disabled={!body.trim()||sending||chatState==="connecting"}>{sending?"Sending…":"Send"}</button></div>{sendError&&<p className="cs-live-send-error" role="alert">{sendError}</p>}</>:<div className="cs-live-signin"><strong>Sign in to join the conversation.</strong><a href="/signin">Sign in</a></div>}</form>
   </aside>
  </div>
 </div>;
}
