"use client";
import Link from "next/link";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {getSupabaseBrowserClient} from "@/lib/supabaseClient";

type MarketCoin={id:string;symbol:string;name:string;price:number;change24h:number;image:string;rank:number|null};
type Holding={id:string;symbol:string;name:string;quantity:number;averagePrice:number;coinId?:string};
const KEY="csl-portfolio-v1";
const CLOUD_KEY="portfolio_v1";

function money(n:number){return n.toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:n>=1000?0:2})}
function readLocal():Holding[]{if(typeof window==="undefined")return[];try{const v=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(v)?v:[]}catch{return[]}}
function validHolding(x:unknown):x is Holding{if(!x||typeof x!=="object")return false;const h=x as Holding;return typeof h.id==="string"&&typeof h.symbol==="string"&&typeof h.name==="string"&&Number.isFinite(h.quantity)&&Number.isFinite(h.averagePrice)}
function mergeHoldings(a:Holding[],b:Holding[]){const map=new Map<string,Holding>();for(const h of [...a,...b])if(validHolding(h))map.set(h.id,h);return [...map.values()]}

export default function PortfolioClient({market}:{market:MarketCoin[]}){
 const[holdings,setHoldings]=useState<Holding[]>([]);const[symbol,setSymbol]=useState("");const[name,setName]=useState("");const[quantity,setQuantity]=useState("");const[price,setPrice]=useState("");const[signedIn,setSignedIn]=useState(false);const[syncReady,setSyncReady]=useState(false);const[syncing,setSyncing]=useState(false);const[syncStatus,setSyncStatus]=useState("Checking account sync…");
 useEffect(()=>{let active=true;(async()=>{const local=readLocal();try{const supabase=getSupabaseBrowserClient();const{data:{user}}=await supabase.auth.getUser();if(!active)return;if(!user){setSignedIn(false);setHoldings(local);setSyncStatus("Saved on this device. Sign in to keep the same portfolio on phone and desktop.");setSyncReady(true);return;}const remoteRaw=user.user_metadata?.[CLOUD_KEY];const remote=Array.isArray(remoteRaw)?remoteRaw.filter(validHolding):[];const merged=mergeHoldings(remote,local);localStorage.setItem(KEY,JSON.stringify(merged));setHoldings(merged);setSignedIn(true);setSyncStatus(`Cloud sync on · ${merged.length} holding${merged.length===1?"":"s"}`);if(JSON.stringify(merged)!==JSON.stringify(remote))await supabase.auth.updateUser({data:{[CLOUD_KEY]:merged}});setSyncReady(true);}catch{if(active){setHoldings(local);setSignedIn(false);setSyncStatus("Cloud sync unavailable. Your local portfolio is still safe on this device.");setSyncReady(true);}}})();return()=>{active=false}},[]);
 async function save(next:Holding[]){setHoldings(next);localStorage.setItem(KEY,JSON.stringify(next));if(!signedIn)return;setSyncing(true);try{const supabase=getSupabaseBrowserClient();const{error}=await supabase.auth.updateUser({data:{[CLOUD_KEY]:next}});if(error)throw error;setSyncStatus(`Cloud sync on · ${next.length} holding${next.length===1?"":"s"}`);}catch{setSyncStatus("Cloud sync could not update. Changes remain saved on this device.");}finally{setSyncing(false)}}
 const marketBySymbol=useMemo(()=>{const m=new Map<string,MarketCoin>();for(const c of market)if(!m.has(c.symbol.toUpperCase()))m.set(c.symbol.toUpperCase(),c);return m},[market]);
 function add(e:FormEvent){e.preventDefault();const q=Number(quantity),p=Number(price),ticker=symbol.trim().toUpperCase();if(!ticker||!Number.isFinite(q)||q<=0||!Number.isFinite(p)||p<0)return;const match=marketBySymbol.get(ticker);void save([...holdings,{id:crypto.randomUUID(),symbol:ticker,name:name.trim()||match?.name||ticker,quantity:q,averagePrice:p,coinId:match?.id}]);setSymbol("");setName("");setQuantity("");setPrice("")}
 const enriched=useMemo(()=>holdings.map(h=>{const m=(h.coinId?market.find(x=>x.id===h.coinId):undefined)||marketBySymbol.get(h.symbol.toUpperCase());const cost=h.quantity*h.averagePrice;const current=m?h.quantity*m.price:null;const pnl=current==null?null:current-cost;const pnlPct=pnl==null||cost===0?null:pnl/cost*100;const dayMove=current==null?null:current*(m!.change24h/100);return{...h,market:m,cost,current,pnl,pnlPct,dayMove}}),[holdings,market,marketBySymbol]);
 const invested=useMemo(()=>enriched.reduce((s,h)=>s+h.cost,0),[enriched]);const liveValue=useMemo(()=>enriched.reduce((s,h)=>s+(h.current??h.cost),0),[enriched]);const totalPnl=liveValue-invested;const totalPnlPct=invested?totalPnl/invested*100:0;const dayMove=useMemo(()=>enriched.reduce((s,h)=>s+(h.dayMove??0),0),[enriched]);const liveRows=enriched.filter(h=>h.current!=null);const best=[...liveRows].sort((a,b)=>(b.pnlPct??-Infinity)-(a.pnlPct??-Infinity))[0];const worst=[...liveRows].sort((a,b)=>(a.pnlPct??Infinity)-(b.pnlPct??Infinity))[0];const largest=[...enriched].sort((a,b)=>(b.current??b.cost)-(a.current??a.cost))[0];
 return <div className="csl2-portfolio-shell"><section className="csl2-page-hero"><div className="csl2-portfolio-head"><div><p className="csl-kicker">Portfolio Intelligence</p><h1 className="csl2-page-title mt-3">See what you own.<br/><span className="csl-gradient-text">Understand what changed.</span></h1><p className="csl2-page-copy">Live market prices sit on top of your holdings, while signed-in accounts now keep the same portfolio across your devices.</p></div><div className="csl2-cost-card"><p className="text-[10px] font-extrabold uppercase tracking-[.12em] text-white/70">Current value</p><p className="mt-2 text-3xl font-black tracking-[-.05em]">{money(liveValue)}</p><p className={`mt-2 text-sm font-bold ${totalPnl>=0?"text-emerald-200":"text-rose-200"}`}>{totalPnl>=0?"+":""}{money(totalPnl)} · {totalPnl>=0?"+":""}{totalPnlPct.toFixed(2)}%</p></div></div></section>
 <div className={`mt-5 rounded-[22px] border px-4 py-3.5 ${signedIn?"border-emerald-100 bg-emerald-50/80":"border-blue-100 bg-white/85"}`}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className={`text-xs font-extrabold ${signedIn?"text-emerald-800":"text-slate-800"}`}>{signedIn?"Portfolio cloud sync is on":"Portfolio is device-only"}</p><p className={`mt-1 text-[11px] leading-5 ${signedIn?"text-emerald-700":"text-slate-500"}`}>{syncReady?syncStatus:"Checking account sync…"}{syncing?" · Saving…":""}</p></div>{!signedIn&&syncReady&&<Link href="/signin" className="csl-btn-primary">Sign in to sync</Link>}</div></div>
 <div className="csl2-summary-grid"><div className="csl2-summary-card"><span>Cost basis</span><strong className="text-[20px]">{money(invested)}</strong></div><div className="csl2-summary-card"><span>24h portfolio move</span><strong className={`text-[20px] ${dayMove>=0?"text-emerald-600":"text-rose-600"}`}>{dayMove>=0?"+":""}{money(dayMove)}</strong></div><div className="csl2-summary-card"><span>Best performer</span><strong className="text-[18px]">{best?`${best.symbol} ${best.pnlPct!>=0?"+":""}${best.pnlPct!.toFixed(1)}%`:"—"}</strong></div><div className="csl2-summary-card"><span>Largest position</span><strong className="text-[18px]">{largest?.symbol||"—"}</strong></div></div>
 <form onSubmit={add} className="csl2-portfolio-form"><input value={symbol} onChange={e=>setSymbol(e.target.value)} placeholder="Ticker, e.g. ZEC" className="csl2-input"/><input value={name} onChange={e=>setName(e.target.value)} placeholder="Coin name (optional)" className="csl2-input"/><input value={quantity} onChange={e=>setQuantity(e.target.value)} inputMode="decimal" placeholder="Quantity" className="csl2-input"/><input value={price} onChange={e=>setPrice(e.target.value)} inputMode="decimal" placeholder="Average buy price $" className="csl2-input"/><button className="csl-btn-primary">Add holding</button></form>
 <div className="csl2-portfolio-list"><div className="hidden grid-cols-[1.35fr_.72fr_.8fr_.85fr_.8fr_.78fr_auto] gap-3 border-b border-slate-100 px-5 py-4 text-[9px] font-extrabold uppercase tracking-[.1em] text-slate-400 lg:grid"><span>Asset</span><span>Quantity</span><span>Avg price</span><span>Live price</span><span>Value</span><span>P/L</span><span/></div>{enriched.length?enriched.map(h=>{const weight=liveValue?(h.current??h.cost)/liveValue*100:0;return <div key={h.id} className="border-b border-slate-100 px-5 py-4 last:border-0"><div className="grid items-center gap-3 lg:grid-cols-[1.35fr_.72fr_.8fr_.85fr_.8fr_.78fr_auto]"><div className="flex min-w-0 items-center gap-3">{h.market?.image?<img src={h.market.image} alt="" className="h-9 w-9 rounded-full"/>:<span className="h-9 w-9 rounded-full bg-slate-100"/>}<div className="min-w-0"><strong className="block truncate text-slate-950">{h.name}</strong><span className="text-[10px] font-bold text-slate-400">{h.symbol}{h.market?.rank?` · #${h.market.rank}`:""}</span></div></div><span className="text-sm">{h.quantity}</span><span className="text-sm">{money(h.averagePrice)}</span><span className="text-sm font-semibold">{h.market?money(h.market.price):"Not matched"}</span><span className="text-sm font-extrabold">{money(h.current??h.cost)}</span><span className={`text-sm font-extrabold ${h.pnl==null?"text-slate-400":h.pnl>=0?"text-emerald-600":"text-rose-600"}`}>{h.pnl==null?"—":`${h.pnl>=0?"+":""}${money(h.pnl)} (${h.pnlPct!.toFixed(1)}%)`}</span><button onClick={()=>void save(holdings.filter(x=>x.id!==h.id))} disabled={syncing} className="rounded-full bg-rose-50 px-3 py-1.5 text-[10px] font-bold text-rose-600 disabled:opacity-50">Remove</button></div><div className="mt-3 flex items-center gap-3"><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-blue-500 via-indigo-500 to-violet-500" style={{width:`${Math.max(2,weight)}%`}}/></div><span className="w-14 text-right text-[10px] font-bold text-slate-400">{weight.toFixed(1)}%</span></div>{h.market&&<div className="mt-2 flex gap-3 text-[10px] font-semibold text-slate-400"><span>24h {h.market.change24h>=0?"+":""}{h.market.change24h.toFixed(2)}%</span><span>Allocation {weight.toFixed(1)}%</span></div>}</div>}):<div className="p-10 text-center"><p className="text-sm font-semibold text-slate-500">No holdings yet.</p><p className="mt-1 text-xs text-slate-400">Add your first asset above to activate Portfolio Intelligence.</p></div>}</div>
 {enriched.length>1&&<div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="csl2-summary-card"><span>Best performer</span><strong className="text-[18px]">{best?`${best.name} · ${best.pnlPct!>=0?"+":""}${best.pnlPct!.toFixed(2)}%`:"—"}</strong></div><div className="csl2-summary-card"><span>Weakest performer</span><strong className="text-[18px]">{worst?`${worst.name} · ${worst.pnlPct!>=0?"+":""}${worst.pnlPct!.toFixed(2)}%`:"—"}</strong></div></div>}
 <p className="mt-4 text-center text-[10px] leading-5 text-slate-400">Signed-in portfolios sync through your CoinSparkLine account. A local copy remains on this device for resilience. Live prices cover the top 250 market-cap assets and refresh periodically.</p></div>}
