"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";

type MarketCoin={id:string;symbol:string;name:string;price:number;change24h:number;image:string;rank:number|null};
type Holding={id:string;symbol:string;name:string;quantity:number;averagePrice:number;coinId?:string};
const KEY="csl-portfolio-v1";

function money(n:number){return n.toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:n>=1000?0:2})}

export default function PortfolioClient({market}:{market:MarketCoin[]}){
 const[holdings,setHoldings]=useState<Holding[]>([]);const[symbol,setSymbol]=useState("");const[name,setName]=useState("");const[quantity,setQuantity]=useState("");const[price,setPrice]=useState("");
 useEffect(()=>{try{setHoldings(JSON.parse(localStorage.getItem(KEY)||"[]"))}catch{setHoldings([])}},[]);
 function save(next:Holding[]){setHoldings(next);localStorage.setItem(KEY,JSON.stringify(next))}
 const marketBySymbol=useMemo(()=>{const m=new Map<string,MarketCoin>();for(const c of market)if(!m.has(c.symbol.toUpperCase()))m.set(c.symbol.toUpperCase(),c);return m},[market]);
 function add(e:FormEvent){e.preventDefault();const q=Number(quantity),p=Number(price),ticker=symbol.trim().toUpperCase();if(!ticker||!Number.isFinite(q)||q<=0||!Number.isFinite(p)||p<0)return;const match=marketBySymbol.get(ticker);save([...holdings,{id:crypto.randomUUID(),symbol:ticker,name:name.trim()||match?.name||ticker,quantity:q,averagePrice:p,coinId:match?.id}]);setSymbol("");setName("");setQuantity("");setPrice("")}
 const enriched=useMemo(()=>holdings.map(h=>{const m=(h.coinId?market.find(x=>x.id===h.coinId):undefined)||marketBySymbol.get(h.symbol.toUpperCase());const cost=h.quantity*h.averagePrice;const current=m?h.quantity*m.price:null;const pnl=current==null?null:current-cost;const pnlPct=pnl==null||cost===0?null:pnl/cost*100;const dayMove=current==null?null:current*(m!.change24h/100);return{...h,market:m,cost,current,pnl,pnlPct,dayMove}}),[holdings,market,marketBySymbol]);
 const invested=useMemo(()=>enriched.reduce((s,h)=>s+h.cost,0),[enriched]);
 const liveValue=useMemo(()=>enriched.reduce((s,h)=>s+(h.current??h.cost),0),[enriched]);
 const totalPnl=liveValue-invested;const totalPnlPct=invested?totalPnl/invested*100:0;
 const dayMove=useMemo(()=>enriched.reduce((s,h)=>s+(h.dayMove??0),0),[enriched]);
 const liveRows=enriched.filter(h=>h.current!=null);
 const best=[...liveRows].sort((a,b)=>(b.pnlPct??-Infinity)-(a.pnlPct??-Infinity))[0];
 const worst=[...liveRows].sort((a,b)=>(a.pnlPct??Infinity)-(b.pnlPct??Infinity))[0];
 const largest=[...enriched].sort((a,b)=>(b.current??b.cost)-(a.current??a.cost))[0];
 return <div className="csl2-portfolio-shell"><section className="csl2-page-hero"><div className="csl2-portfolio-head"><div><p className="csl-kicker">Portfolio Intelligence</p><h1 className="csl2-page-title mt-3">See what you own.<br/><span className="csl-gradient-text">Understand what changed.</span></h1><p className="csl2-page-copy">Live market prices now sit on top of your private holdings, so CoinSparkLine can show value, profit/loss, allocation and daily movement without turning the portfolio into a trading recommendation.</p></div><div className="csl2-cost-card"><p className="text-[10px] font-extrabold uppercase tracking-[.12em] text-white/70">Current value</p><p className="mt-2 text-3xl font-black tracking-[-.05em]">{money(liveValue)}</p><p className={`mt-2 text-sm font-bold ${totalPnl>=0?"text-emerald-200":"text-rose-200"}`}>{totalPnl>=0?"+":""}{money(totalPnl)} · {totalPnl>=0?"+":""}{totalPnlPct.toFixed(2)}%</p></div></div></section>
 <div className="csl2-summary-grid"><div className="csl2-summary-card"><span>Cost basis</span><strong className="text-[20px]">{money(invested)}</strong></div><div className="csl2-summary-card"><span>24h portfolio move</span><strong className={`text-[20px] ${dayMove>=0?"text-emerald-600":"text-rose-600"}`}>{dayMove>=0?"+":""}{money(dayMove)}</strong></div><div className="csl2-summary-card"><span>Best performer</span><strong className="text-[18px]">{best?`${best.symbol} ${best.pnlPct!>=0?"+":""}${best.pnlPct!.toFixed(1)}%`:"—"}</strong></div><div className="csl2-summary-card"><span>Largest position</span><strong className="text-[18px]">{largest?.symbol||"—"}</strong></div></div>
 <form onSubmit={add} className="csl2-portfolio-form"><input value={symbol} onChange={e=>setSymbol(e.target.value)} placeholder="Ticker, e.g. ZEC" className="csl2-input"/><input value={name} onChange={e=>setName(e.target.value)} placeholder="Coin name (optional)" className="csl2-input"/><input value={quantity} onChange={e=>setQuantity(e.target.value)} inputMode="decimal" placeholder="Quantity" className="csl2-input"/><input value={price} onChange={e=>setPrice(e.target.value)} inputMode="decimal" placeholder="Average buy price $" className="csl2-input"/><button className="csl-btn-primary">Add holding</button></form>
 <div className="csl2-portfolio-list"><div className="hidden grid-cols-[1.35fr_.72fr_.8fr_.85fr_.8fr_.78fr_auto] gap-3 border-b border-slate-100 px-5 py-4 text-[9px] font-extrabold uppercase tracking-[.1em] text-slate-400 lg:grid"><span>Asset</span><span>Quantity</span><span>Avg price</span><span>Live price</span><span>Value</span><span>P/L</span><span/></div>{enriched.length?enriched.map(h=>{const weight=liveValue?(h.current??h.cost)/liveValue*100:0;return <div key={h.id} className="border-b border-slate-100 px-5 py-4 last:border-0"><div className="grid items-center gap-3 lg:grid-cols-[1.35fr_.72fr_.8fr_.85fr_.8fr_.78fr_auto]"><div className="flex min-w-0 items-center gap-3">{h.market?.image?<img src={h.market.image} alt="" className="h-9 w-9 rounded-full"/>:<span className="h-9 w-9 rounded-full bg-slate-100"/>}<div className="min-w-0"><strong className="block truncate text-slate-950">{h.name}</strong><span className="text-[10px] font-bold text-slate-400">{h.symbol}{h.market?.rank?` · #${h.market.rank}`:""}</span></div></div><span className="text-sm">{h.quantity}</span><span className="text-sm">{money(h.averagePrice)}</span><span className="text-sm font-semibold">{h.market?money(h.market.price):"Not matched"}</span><span className="text-sm font-extrabold">{money(h.current??h.cost)}</span><span className={`text-sm font-extrabold ${h.pnl==null?"text-slate-400":h.pnl>=0?"text-emerald-600":"text-rose-600"}`}>{h.pnl==null?"—":`${h.pnl>=0?"+":""}${money(h.pnl)} (${h.pnlPct!.toFixed(1)}%)`}</span><button onClick={()=>save(holdings.filter(x=>x.id!==h.id))} className="rounded-full bg-rose-50 px-3 py-1.5 text-[10px] font-bold text-rose-600">Remove</button></div><div className="mt-3 flex items-center gap-3"><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-blue-500 via-indigo-500 to-violet-500" style={{width:`${Math.max(2,weight)}%`}}/></div><span className="w-14 text-right text-[10px] font-bold text-slate-400">{weight.toFixed(1)}%</span></div>{h.market&&<div className="mt-2 flex gap-3 text-[10px] font-semibold text-slate-400"><span>24h {h.market.change24h>=0?"+":""}{h.market.change24h.toFixed(2)}%</span><span>Allocation {weight.toFixed(1)}%</span></div>}</div>}):<div className="p-10 text-center"><p className="text-sm font-semibold text-slate-500">No holdings yet.</p><p className="mt-1 text-xs text-slate-400">Add your first asset above to activate Portfolio Intelligence.</p></div>}</div>
 {enriched.length>1&&<div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="csl2-summary-card"><span>Best performer</span><strong className="text-[18px]">{best?`${best.name} · ${best.pnlPct!>=0?"+":""}${best.pnlPct!.toFixed(2)}%`:"—"}</strong></div><div className="csl2-summary-card"><span>Weakest performer</span><strong className="text-[18px]">{worst?`${worst.name} · ${worst.pnlPct!>=0?"+":""}${worst.pnlPct!.toFixed(2)}%`:"—"}</strong></div></div>}
 <p className="mt-4 text-center text-[10px] leading-5 text-slate-400">Holdings remain stored locally in this browser. Live prices cover the top 250 market-cap assets and refresh periodically.</p></div>}
