"use client";
import Link from "next/link";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {getSupabaseBrowserClient} from "@/lib/supabaseClient";

type MarketCoin={id:string;symbol:string;name:string;price:number;change24h:number;image:string;rank:number|null};
type TxType="BUY"|"SELL"|"TRANSFER_IN"|"TRANSFER_OUT";
type Tx={id:string;type:TxType;symbol:string;name:string;quantity:number;price:number;coinId?:string;createdAt:string};
type Holding={id:string;symbol:string;name:string;quantity:number;averagePrice:number;coinId?:string};
const TX_KEY="csl-portfolio-transactions-v1";const CLOUD_KEY="portfolio_transactions_v1";const OLD_KEY="csl-portfolio-v1";
function money(n:number){return n.toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:n>=1000?0:2})}
function readTx():Tx[]{try{const x=JSON.parse(localStorage.getItem(TX_KEY)||"[]");return Array.isArray(x)?x:[]}catch{return[]}}
function validTx(x:any):x is Tx{return x&&typeof x.id==="string"&&["BUY","SELL","TRANSFER_IN","TRANSFER_OUT"].includes(x.type)&&typeof x.symbol==="string"&&Number.isFinite(x.quantity)&&Number.isFinite(x.price)}
function mergeTx(a:Tx[],b:Tx[]){const m=new Map<string,Tx>();[...a,...b].filter(validTx).forEach(x=>m.set(x.id,x));return [...m.values()].sort((a,b)=>a.createdAt.localeCompare(b.createdAt))}
function buildHoldings(txs:Tx[]):Holding[]{const m=new Map<string,Holding>();for(const t of txs){const key=t.coinId||t.symbol;const h=m.get(key)||{id:key,symbol:t.symbol,name:t.name,quantity:0,averagePrice:0,coinId:t.coinId};if(t.type==="BUY"){const cost=h.quantity*h.averagePrice+t.quantity*t.price;h.quantity+=t.quantity;h.averagePrice=h.quantity?cost/h.quantity:0}else if(t.type==="TRANSFER_IN"){h.quantity+=t.quantity}else if(t.type==="SELL"||t.type==="TRANSFER_OUT"){h.quantity=Math.max(0,h.quantity-t.quantity);if(h.quantity===0)h.averagePrice=0}m.set(key,h)}return [...m.values()].filter(h=>h.quantity>0)}
export default function PortfolioClient({market}:{market:MarketCoin[]}){
 const[txs,setTxs]=useState<Tx[]>([]);const[type,setType]=useState<TxType>("BUY");const[symbol,setSymbol]=useState("");const[quantity,setQuantity]=useState("");const[price,setPrice]=useState("");const[signedIn,setSignedIn]=useState(false);const[syncReady,setSyncReady]=useState(false);const[syncing,setSyncing]=useState(false);const[syncStatus,setSyncStatus]=useState("Checking account sync…");
 const marketBySymbol=useMemo(()=>{const m=new Map<string,MarketCoin>();market.forEach(c=>{if(!m.has(c.symbol.toUpperCase()))m.set(c.symbol.toUpperCase(),c)});return m},[market]);
 useEffect(()=>{let active=true;(async()=>{let local=readTx();if(!local.length){try{const old=JSON.parse(localStorage.getItem(OLD_KEY)||"[]");if(Array.isArray(old))local=old.map((h:any)=>({id:`migration-${h.id}`,type:"BUY" as TxType,symbol:h.symbol,name:h.name,quantity:h.quantity,price:h.averagePrice,coinId:h.coinId,createdAt:new Date().toISOString()})).filter(validTx)}catch{}}try{const s=getSupabaseBrowserClient();const{data:{user}}=await s.auth.getUser();if(!active)return;if(!user){setTxs(local);setSyncStatus("Transactions are saved on this device. Sign in to sync them.");setSyncReady(true);return}const remote=Array.isArray(user.user_metadata?.[CLOUD_KEY])?user.user_metadata[CLOUD_KEY].filter(validTx):[];const merged=mergeTx(remote,local);localStorage.setItem(TX_KEY,JSON.stringify(merged));setTxs(merged);setSignedIn(true);setSyncStatus(`Cloud sync on · ${merged.length} transaction${merged.length===1?"":"s"}`);if(JSON.stringify(merged)!==JSON.stringify(remote))await s.auth.updateUser({data:{[CLOUD_KEY]:merged}});setSyncReady(true)}catch{if(active){setTxs(local);setSyncStatus("Cloud sync unavailable. Transactions remain safe on this device.");setSyncReady(true)}}})();return()=>{active=false}},[]);
 async function save(next:Tx[]){setTxs(next);localStorage.setItem(TX_KEY,JSON.stringify(next));if(!signedIn)return;setSyncing(true);try{const s=getSupabaseBrowserClient();const{error}=await s.auth.updateUser({data:{[CLOUD_KEY]:next}});if(error)throw error;setSyncStatus(`Cloud sync on · ${next.length} transaction${next.length===1?"":"s"}`)}catch{setSyncStatus("Cloud sync could not update. Changes remain saved locally.")}finally{setSyncing(false)}}
 const holdings=useMemo(()=>buildHoldings(txs),[txs]);
 function addTx(e:FormEvent){e.preventDefault();const ticker=symbol.trim().toUpperCase(),q=Number(quantity),p=Number(price||0);if(!ticker||!Number.isFinite(q)||q<=0||!Number.isFinite(p)||p<0)return;const match=marketBySymbol.get(ticker);const current=holdings.find(h=>(h.coinId&&h.coinId===match?.id)||h.symbol===ticker);if((type==="SELL"||type==="TRANSFER_OUT")&&(!current||q>current.quantity))return;void save([...txs,{id:crypto.randomUUID(),type,symbol:ticker,name:match?.name||ticker,quantity:q,price:(type==="TRANSFER_IN"||type==="TRANSFER_OUT")?0:p,coinId:match?.id,createdAt:new Date().toISOString()}]);setSymbol("");setQuantity("");setPrice("")}
 const enriched=useMemo(()=>holdings.map(h=>{const m=(h.coinId?market.find(x=>x.id===h.coinId):undefined)||marketBySymbol.get(h.symbol);const cost=h.quantity*h.averagePrice,current=m?h.quantity*m.price:null,pnl=current==null?null:current-cost,pnlPct=pnl==null||!cost?null:pnl/cost*100;return{...h,market:m,cost,current,pnl,pnlPct,dayMove:current==null?0:current*(m!.change24h/100)}}),[holdings,market,marketBySymbol]);
 const invested=enriched.reduce((s,h)=>s+h.cost,0),liveValue=enriched.reduce((s,h)=>s+(h.current??h.cost),0),totalPnl=liveValue-invested,totalPnlPct=invested?totalPnl/invested*100:0,dayMove=enriched.reduce((s,h)=>s+h.dayMove,0);const liveRows=enriched.filter(h=>h.current!=null),best=[...liveRows].sort((a,b)=>(b.pnlPct??-Infinity)-(a.pnlPct??-Infinity))[0],largest=[...enriched].sort((a,b)=>(b.current??b.cost)-(a.current??a.cost))[0];
 return <div className="csl2-portfolio-shell"><section className="csl2-page-hero"><div className="csl2-portfolio-head"><div><p className="csl-kicker">Portfolio Intelligence · Step 3</p><h1 className="csl2-page-title mt-3">Record every move.<br/><span className="csl-gradient-text">Let the portfolio calculate itself.</span></h1><p className="csl2-page-copy">Buy, sell and transfer transactions now drive your holdings automatically. Average cost updates as buys are added, while sells and transfers adjust quantity.</p></div><div className="csl2-cost-card"><p className="text-[10px] font-extrabold uppercase tracking-[.12em] text-white/70">Current value</p><p className="mt-2 text-3xl font-black">{money(liveValue)}</p><p className={`mt-2 text-sm font-bold ${totalPnl>=0?"text-emerald-200":"text-rose-200"}`}>{totalPnl>=0?"+":""}{money(totalPnl)} · {totalPnlPct.toFixed(2)}%</p></div></div></section>
 <div className={`mt-5 rounded-[22px] border px-4 py-3.5 ${signedIn?"border-emerald-100 bg-emerald-50/80":"border-blue-100 bg-white/85"}`}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-extrabold text-slate-800">{signedIn?"Transaction cloud sync is on":"Transactions are device-only"}</p><p className="mt-1 text-[11px] text-slate-500">{syncReady?syncStatus:"Checking account sync…"}{syncing?" · Saving…":""}</p></div>{!signedIn&&syncReady&&<Link href="/signin" className="csl-btn-primary">Sign in to sync</Link>}</div></div>
 <div className="csl2-summary-grid"><div className="csl2-summary-card"><span>Cost basis</span><strong>{money(invested)}</strong></div><div className="csl2-summary-card"><span>24h move</span><strong className={dayMove>=0?"text-emerald-600":"text-rose-600"}>{dayMove>=0?"+":""}{money(dayMove)}</strong></div><div className="csl2-summary-card"><span>Best performer</span><strong>{best?`${best.symbol} ${best.pnlPct!>=0?"+":""}${best.pnlPct!.toFixed(1)}%`:"—"}</strong></div><div className="csl2-summary-card"><span>Largest position</span><strong>{largest?.symbol||"—"}</strong></div></div>
 <section className="mt-5 rounded-[28px] border border-blue-100 bg-white/90 p-5 shadow-sm"><div className="mb-4"><p className="csl-kicker">Add transaction</p><h2 className="mt-1 text-xl font-black text-slate-950">What happened?</h2></div><form onSubmit={addTx} className="grid gap-3 md:grid-cols-5"><select value={type} onChange={e=>setType(e.target.value as TxType)} className="csl2-input"><option value="BUY">Buy</option><option value="SELL">Sell</option><option value="TRANSFER_IN">Transfer in</option><option value="TRANSFER_OUT">Transfer out</option></select><input value={symbol} onChange={e=>setSymbol(e.target.value)} placeholder="Ticker, e.g. ZEC" className="csl2-input"/><input value={quantity} onChange={e=>setQuantity(e.target.value)} inputMode="decimal" placeholder="Quantity" className="csl2-input"/>{type==="BUY"||type==="SELL"?<input value={price} onChange={e=>setPrice(e.target.value)} inputMode="decimal" placeholder="Price per coin $" className="csl2-input"/>:<div className="csl2-input flex items-center text-xs text-slate-400">No price needed</div>}<button className="csl-btn-primary">Add transaction</button></form></section>
 <div className="csl2-portfolio-list mt-5">{enriched.length?enriched.map(h=>{const weight=liveValue?(h.current??h.cost)/liveValue*100:0;return <div key={h.id} className="border-b border-slate-100 px-5 py-5 last:border-0"><div className="grid items-center gap-3 lg:grid-cols-[1.4fr_.7fr_.8fr_.8fr_.8fr]"><div className="flex items-center gap-3">{h.market?.image?<img src={h.market.image} alt="" className="h-10 w-10 rounded-full"/>:<span className="h-10 w-10 rounded-full bg-slate-100"/>}<div><strong>{h.name}</strong><p className="text-[10px] font-bold text-slate-400">{h.symbol}</p></div></div><div><span className="text-[9px] uppercase text-slate-400">Quantity</span><p className="font-bold">{h.quantity}</p></div><div><span className="text-[9px] uppercase text-slate-400">Avg cost</span><p className="font-bold">{money(h.averagePrice)}</p></div><div><span className="text-[9px] uppercase text-slate-400">Value</span><p className="font-bold">{money(h.current??h.cost)}</p></div><div><span className="text-[9px] uppercase text-slate-400">P/L</span><p className={`font-bold ${h.pnl==null?"text-slate-400":h.pnl>=0?"text-emerald-600":"text-rose-600"}`}>{h.pnl==null?"—":`${h.pnl>=0?"+":""}${money(h.pnl)}`}</p></div></div><div className="mt-3 flex items-center gap-3"><div className="h-1.5 flex-1 rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-blue-500 to-violet-500" style={{width:`${Math.max(2,weight)}%`}}/></div><span className="text-[10px] font-bold text-slate-400">{weight.toFixed(1)}%</span></div></div>}):<div className="p-10 text-center text-sm text-slate-500">No active holdings. Add a Buy or Transfer in transaction above.</div>}</div>
 <section className="mt-5 rounded-[28px] border border-slate-100 bg-white/90 p-5"><div className="flex items-end justify-between"><div><p className="csl-kicker">Ledger</p><h2 className="mt-1 text-xl font-black">Transaction history</h2></div><span className="text-xs font-bold text-slate-400">{txs.length} total</span></div><div className="mt-4 space-y-2">{[...txs].reverse().slice(0,30).map(t=><div key={t.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-slate-50 px-4 py-3"><div><strong className="text-sm">{t.type.replace("_"," ")} · {t.symbol}</strong><p className="text-[10px] text-slate-400">{new Date(t.createdAt).toLocaleString()}</p></div><div className="text-right"><p className="text-sm font-bold">{t.quantity} {t.symbol}</p><p className="text-[10px] text-slate-400">{t.type==="BUY"||t.type==="SELL"?`@ ${money(t.price)}`:"Quantity only"}</p></div></div>)}</div></section>
 <p className="mt-4 text-center text-[10px] leading-5 text-slate-400">Average cost uses weighted-average accounting for recorded buys. Transfers do not create a purchase cost. This is portfolio tracking, not tax accounting or financial advice.</p></div>}
