"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
import CurrencyAmount from "@/components/CurrencyAmount";
import WatchlistButton from "@/components/WatchlistButton";
import AlertRuleButton from "@/components/AlertRuleButton";
import {Coin} from "@/types/coin";
import {getSignalTier,TIER_CONFIG} from "@/lib/tiers";
import {getSparkScore} from "@/lib/sparkScore";

type PrivacyProfile={
 id:string;short:string;privacy:string;defaultMode:string;technology:string;focus:string;wallets:string[];notes:string;
};

const PROFILES:PrivacyProfile[]=[
 {id:"monero",short:"XMR",privacy:"Default",defaultMode:"Private by default",technology:"Ring signatures · stealth addresses · confidential amounts",focus:"Private digital cash",wallets:["Monero GUI","Feather","Cake Wallet","Ledger integration"],notes:"Privacy is built into normal transfers rather than offered as an optional mode."},
 {id:"zcash",short:"ZEC",privacy:"Optional",defaultMode:"Transparent + shielded",technology:"Zero-knowledge proofs (zk-SNARKs)",focus:"Selective disclosure and shielded payments",wallets:["Zashi","YWallet","Zecwallet Lite"],notes:"Users can choose shielded transactions, while transparent addresses also exist."},
 {id:"firo",short:"FIRO",privacy:"Optional",defaultMode:"Private transaction tools",technology:"Lelantus Spark",focus:"Private payments with strong unlinkability",wallets:["Firo Core","Campfire","Electrum-Firo"],notes:"Firo focuses on practical privacy features while retaining transparent transaction paths."},
 {id:"dash",short:"DASH",privacy:"Optional",defaultMode:"PrivateSend optional",technology:"CoinJoin-style mixing",focus:"Payments and optional transaction privacy",wallets:["Dash Core","Dash Wallet","Ledger"],notes:"Dash is primarily a payments network; its privacy approach differs materially from Zcash, Monero and Firo."},
 {id:"pirate-chain",short:"ARRR",privacy:"Default",defaultMode:"Shielded by default",technology:"zk-SNARK shielded transactions",focus:"Privacy-first payments",wallets:["Treasure Chest","Pirate Wallet Lite","Mobile wallets"],notes:"Designed around mandatory shielded transactions for ordinary wallet activity."},
 {id:"beam",short:"BEAM",privacy:"Default",defaultMode:"Confidential by design",technology:"Mimblewimble",focus:"Confidential value transfer",wallets:["Beam Wallet"],notes:"Uses the Mimblewimble model, which approaches transaction privacy differently from shielded-address systems."},
];

function tone(tier:string){const c=TIER_CONFIG[tier as keyof typeof TIER_CONFIG];return c||TIER_CONFIG.calm}

export default function PrivacyCoinHub({coins}:{coins:Coin[]}){
 const[query,setQuery]=useState("");const[mode,setMode]=useState<"all"|"default"|"optional">("all");
 const map=useMemo(()=>new Map(coins.map(c=>[c.id,c])),[coins]);
 const rows=useMemo(()=>PROFILES.map(p=>({profile:p,coin:map.get(p.id)})).filter(x=>{const q=query.trim().toLowerCase();const match=!q||x.profile.id.includes(q)||x.profile.short.toLowerCase().includes(q)||x.coin?.name.toLowerCase().includes(q);const modeMatch=mode==="all"||(mode==="default"?x.profile.privacy==="Default":x.profile.privacy==="Optional");return match&&modeMatch}),[map,query,mode]);
 const tracked=rows.filter(r=>r.coin).length;const strongest=[...rows].filter(r=>r.coin).sort((a,b)=>getSparkScore(b.coin!).score-getSparkScore(a.coin!).score)[0];
 return <>
  <section className="csl2-page-hero"><div className="grid gap-8 lg:grid-cols-[1fr_.8fr] lg:items-end"><div><p className="csl-kicker">Privacy Coin Hub</p><h1 className="csl2-page-title mt-3">Privacy is not one technology.<br/><span className="csl-gradient-text">Compare the different approaches.</span></h1><p className="csl2-page-copy">Compare privacy design, transaction model and live CoinSparkLine behaviour for major privacy-focused cryptocurrencies in one place.</p></div><div className="grid grid-cols-3 gap-2"><div className="csl2-summary-card"><span>Profiles</span><strong>{PROFILES.length}</strong></div><div className="csl2-summary-card"><span>Tracked live</span><strong>{tracked}</strong></div><div className="csl2-summary-card"><span>Top Spark</span><strong>{strongest?.coin?getSparkScore(strongest.coin).score:"—"}</strong></div></div></div></section>

  <section className="mt-5 rounded-[28px] border border-blue-100 bg-white/90 p-5 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="flex flex-wrap gap-2">{[["all","All privacy models"],["default","Private by default"],["optional","Optional privacy"]].map(([k,l])=><button key={k} onClick={()=>setMode(k as any)} className={`rounded-full px-4 py-2 text-[11px] font-extrabold ${mode===k?"bg-gradient-to-r from-blue-600 to-violet-600 text-white":"border border-slate-200 bg-white text-slate-500"}`}>{l}</button>)}</div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Zcash, Monero, Firo…" className="csl2-input md:w-72"/></div></section>

  <section className="mt-5 grid gap-4 xl:grid-cols-2">{rows.map(({profile,coin})=>{const spark=coin?getSparkScore(coin):null;const tier=coin?getSignalTier(coin):null;const cfg=tier?tone(tier):null;return <article key={profile.id} className="rounded-[30px] border border-slate-200/70 bg-white p-5 shadow-[0_16px_45px_rgba(30,64,175,.05)]"><div className="flex items-start justify-between gap-4"><div className="flex min-w-0 items-center gap-3">{coin?.logoUrl?<img src={coin.logoUrl} alt="" className="h-12 w-12 shrink-0 rounded-full object-contain"/>:<div className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-gradient-to-br from-blue-50 to-violet-50 text-[11px] font-black text-indigo-600">{profile.short}</div>}<div className="min-w-0"><h2 className="truncate text-xl font-black tracking-[-.035em] text-slate-950">{coin?.name||profile.id.replace(/-/g," ")}</h2><p className="mt-1 text-[10px] font-bold uppercase tracking-[.13em] text-slate-400">{profile.short} · {profile.focus}</p></div></div>{coin&&<WatchlistButton coinId={coin.id} compact/>}</div>
    <div className="mt-5 grid gap-2 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-3"><span className="text-[9px] font-bold uppercase tracking-[.1em] text-slate-400">Privacy mode</span><p className="mt-1 text-sm font-extrabold text-slate-900">{profile.defaultMode}</p></div><div className="rounded-2xl bg-slate-50 p-3"><span className="text-[9px] font-bold uppercase tracking-[.1em] text-slate-400">Technology</span><p className="mt-1 text-sm font-extrabold text-slate-900">{profile.technology}</p></div><div className="rounded-2xl bg-slate-50 p-3"><span className="text-[9px] font-bold uppercase tracking-[.1em] text-slate-400">Wallet examples</span><p className="mt-1 text-sm font-extrabold text-slate-900">{profile.wallets.slice(0,2).join(" · ")}</p></div></div>
    {coin?<><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><div className="rounded-2xl border border-slate-100 p-3"><span className="text-[9px] uppercase text-slate-400">Price</span><p className="mt-1 font-extrabold"><CurrencyAmount usd={coin.price}/></p></div><div className="rounded-2xl border border-slate-100 p-3"><span className="text-[9px] uppercase text-slate-400">24h</span><p className={`mt-1 font-extrabold ${coin.change24hPct>=0?"text-emerald-600":"text-rose-600"}`}>{coin.change24hPct>=0?"+":""}{coin.change24hPct.toFixed(2)}%</p></div><div className="rounded-2xl border border-slate-100 p-3"><span className="text-[9px] uppercase text-slate-400">SparkScore</span><p className="mt-1 font-extrabold text-indigo-600">{spark!.score}</p></div><div className="rounded-2xl border border-slate-100 p-3"><span className="text-[9px] uppercase text-slate-400">Signal</span><p className={`mt-1 font-extrabold ${cfg!.text}`}>{cfg!.label}</p></div></div><div className="mt-4 flex flex-wrap gap-2"><Link href={`/coin/${coin.id}`} className="csl-btn-primary">Full coin research →</Link><div className="[&>button]:min-h-[40px]"><AlertRuleButton coinId={coin.id}/></div></div></>:<div className="mt-4 rounded-2xl bg-amber-50 px-4 py-3 text-xs leading-5 text-amber-700">This privacy profile is included for comparison, but it is not currently present in the active CoinSparkLine scan universe.</div>}
    <p className="mt-4 text-xs leading-6 text-slate-500">{profile.notes}</p></article>})}</section>

  <section className="mt-5 rounded-[30px] border border-indigo-100 bg-gradient-to-br from-white via-blue-50/70 to-violet-50 p-6"><p className="csl-kicker">How to use this page</p><h2 className="mt-2 text-2xl font-black tracking-[-.04em] text-slate-950">Privacy strength is not a single score.</h2><p className="mt-3 max-w-4xl text-sm leading-7 text-slate-600">Default privacy, optional privacy, cryptographic design, wallet support, exchange access and usability are different dimensions. CoinSparkLine does not rank one privacy model as universally “best”. Market availability can also vary by country and exchange, so use each coin’s research page to check current markets and wallet links before acting.</p></section>
 </>;
}
