"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
import {Coin} from "@/types/coin";
import {getSparkScore} from "@/lib/sparkScore";
import {getSignalTier} from "@/lib/tiers";
import CurrencyAmount from "@/components/CurrencyAmount";
import WatchlistButton from "@/components/WatchlistButton";
import AlertRuleButton from "@/components/AlertRuleButton";
import {Button,Card,EmptyState,Input,PageHero,RegimeBadge,Select,SparkBadge} from "@/components/ui";

type Sort="spark"|"rank"|"confidence"|"streak"|"move";
const regimeLabel={calm:"Calm",building:"Building",awakening:"Awakening",volatile:"Volatile"} as const;
export default function ScreenerClient({coins}:{coins:Coin[]}){
 const[minSpark,setMinSpark]=useState(60),[minRank,setMinRank]=useState(1),[maxRank,setMaxRank]=useState(500),[minConfidence,setMinConfidence]=useState(0),[minStreak,setMinStreak]=useState(0),[maxMove,setMaxMove]=useState(100),[regime,setRegime]=useState("all"),[sort,setSort]=useState<Sort>("spark"),[query,setQuery]=useState("");
 const results=useMemo(()=>{const q=query.trim().toLowerCase();return coins.filter(c=>!["usdt","usdc","dai","busd","tusd","usdp"].includes(c.symbol.toLowerCase())).filter(c=>{const spark=getSparkScore(c).score,tier=getSignalTier(c),rank=c.marketCapRank??99999;return spark>=minSpark&&rank>=minRank&&rank<=maxRank&&c.confidencePct>=minConfidence&&c.streakDays>=minStreak&&Math.abs(c.change24hPct)<=maxMove&&(regime==="all"||tier===regime)&&(!q||c.name.toLowerCase().includes(q)||c.symbol.toLowerCase().includes(q))}).sort((a,b)=>sort==="spark"?getSparkScore(b).score-getSparkScore(a).score:sort==="rank"?(a.marketCapRank??99999)-(b.marketCapRank??99999):sort==="confidence"?b.confidencePct-a.confidencePct:sort==="streak"?b.streakDays-a.streakDays:Math.abs(b.change24hPct)-Math.abs(a.change24hPct))},[coins,minSpark,minRank,maxRank,minConfidence,minStreak,maxMove,regime,sort,query]);
 const reset=()=>{setMinSpark(0);setMinRank(1);setMaxRank(10000);setMinConfidence(0);setMinStreak(0);setMaxMove(100);setRegime("all");setQuery("")};
 return <main className="cs-discovery-page"><div className="cs-discovery-shell"><PageHero eyebrow="Custom screener" title={<>Build your own <span className="csl-gradient-text">market lens.</span></>} description="Filter observable market conditions by SparkScore, rank, confidence, regime, streak and 24h change. The screener shows exactly the conditions you ask for — it does not predict returns."/>
 <Card variant="raised" className="cs-filter-panel"><div className="cs-filter-grid"><label>Minimum SparkScore<input type="range" min="0" max="100" value={minSpark} onChange={e=>setMinSpark(+e.target.value)}/><strong>{minSpark}+</strong></label><label>Market-cap rank<div className="cs-rank-pair"><Input value={minRank} onChange={e=>setMinRank(Math.max(1,+e.target.value||1))} type="number"/><span>to</span><Input value={maxRank} onChange={e=>setMaxRank(Math.max(1,+e.target.value||1))} type="number"/></div></label><label>Minimum confidence<input type="range" min="0" max="100" value={minConfidence} onChange={e=>setMinConfidence(+e.target.value)}/><strong>{minConfidence}%+</strong></label><label>Minimum days in state<input type="range" min="0" max="90" value={minStreak} onChange={e=>setMinStreak(+e.target.value)}/><strong>{minStreak}+ days</strong></label><label>Maximum absolute 24h change<input type="range" min="1" max="100" value={maxMove} onChange={e=>setMaxMove(+e.target.value)}/><strong>±{maxMove}%</strong></label><label>Market regime<Select value={regime} onChange={e=>setRegime(e.target.value)}><option value="all">All regimes</option><option value="calm">Calm</option><option value="building">Building</option><option value="awakening">Awakening</option><option value="volatile">Volatile</option></Select></label><label>Sort results<Select value={sort} onChange={e=>setSort(e.target.value as Sort)}><option value="spark">Highest SparkScore</option><option value="rank">Market-cap rank</option><option value="confidence">Highest confidence</option><option value="streak">Longest streak</option><option value="move">Largest 24h change</option></Select></label><div className="cs-filter-reset"><Button variant="secondary" onClick={reset}>Reset filters</Button></div></div></Card>
 <div className="cs-results-head"><div><p className="cs-eyebrow">Matches</p><h2>{results.length} assets found</h2></div><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search within results…" aria-label="Search within results"/></div>
 {results.length?<div className="cs-result-grid">{results.slice(0,120).map(c=>{const spark=getSparkScore(c),tier=getSignalTier(c),positive=c.change24hPct>=0;return <Card key={c.id} interactive className="cs-result-card"><div className="cs-result-top"><Link href={`/coin/${c.id}`} className="cs-result-coin">{c.logoUrl?<img src={c.logoUrl} alt=""/>:<span/>}<div><strong>{c.name}</strong><small>{c.symbol}{c.marketCapRank?` · #${c.marketCapRank}`:""}</small></div></Link><WatchlistButton coinId={c.id} compact/></div><div className="cs-result-price"><div><strong><CurrencyAmount usd={c.price}/></strong><span data-direction={positive?"up":"down"}>{positive?"+":""}{c.change24hPct.toFixed(2)}%</span></div><SparkBadge score={spark.score}/></div><div className="cs-result-metrics"><RegimeBadge regime={regimeLabel[tier]}/><span>Confidence <b>{c.confidencePct.toFixed(0)}%</b></span><span>Streak <b>{c.streakDays}d</b></span></div><div className="cs-result-actions"><Link href={`/coin/${c.id}`} className="cs-button cs-button--secondary">Research coin</Link><AlertRuleButton coinId={c.id} compact/></div></Card>})}</div>:<EmptyState title="No matching assets" description="Adjust the filters to widen your market screen."/>}
 {results.length>120&&<p className="cs-page-note">Showing the first 120 matches. Tighten the filters to narrow the screen.</p>}<p className="cs-page-note">The screener filters observable market data and CoinSparkLine model states. It does not predict future returns or recommend investments.</p></div></main>;
}
