"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
import {Coin} from "@/types/coin";
import {getSparkScore} from "@/lib/sparkScore";
import {getSignalTier,TIER_CONFIG} from "@/lib/tiers";
import CurrencyAmount from "@/components/CurrencyAmount";
import WatchlistButton from "@/components/WatchlistButton";
import AlertRuleButton from "@/components/AlertRuleButton";

type Sort="spark"|"rank"|"confidence"|"streak"|"move";
export default function ScreenerClient({coins}:{coins:Coin[]}){
 const[minSpark,setMinSpark]=useState(60),[minRank,setMinRank]=useState(1),[maxRank,setMaxRank]=useState(500),[minConfidence,setMinConfidence]=useState(0),[minStreak,setMinStreak]=useState(0),[maxMove,setMaxMove]=useState(100),[regime,setRegime]=useState("all"),[sort,setSort]=useState<Sort>("spark"),[query,setQuery]=useState("");
 const results=useMemo(()=>{const q=query.trim().toLowerCase();return coins.filter(c=>!["usdt","usdc","dai","busd","tusd","usdp"].includes(c.symbol.toLowerCase())).filter(c=>{const spark=getSparkScore(c).score,tier=getSignalTier(c),rank=c.marketCapRank??99999;return spark>=minSpark&&rank>=minRank&&rank<=maxRank&&c.confidencePct>=minConfidence&&c.streakDays>=minStreak&&Math.abs(c.change24hPct)<=maxMove&&(regime==="all"||tier===regime)&&(!q||c.name.toLowerCase().includes(q)||c.symbol.toLowerCase().includes(q))}).sort((a,b)=>sort==="spark"?getSparkScore(b).score-getSparkScore(a).score:sort==="rank"?(a.marketCapRank??99999)-(b.marketCapRank??99999):sort==="confidence"?b.confidencePct-a.confidencePct:sort==="streak"?b.streakDays-a.streakDays:Math.abs(b.change24hPct)-Math.abs(a.change24hPct))},[coins,minSpark,minRank,maxRank,minConfidence,minStreak,maxMove,regime,sort,query]);
 const reset=()=>{setMinSpark(0);setMinRank(1);setMaxRank(10000);setMinConfidence(0);setMinStreak(0);setMaxMove(100);setRegime("all");setQuery("")};
 return <div className="csl-shell py-10"><section className="csl2-page-hero"><p className="csl-kicker">Step 11 · Custom Screener</p><h1 className="csl2-page-title mt-3">Build your own<br/><span className="csl-gradient-text">market lens.</span></h1><p className="csl2-page-copy">Combine CoinSparkLine signals with rank, confidence, streak and price-movement limits. The result updates instantly — no prediction claims, just the market conditions you asked to see.</p></section>
 <section className="mt-6 rounded-[28px] border border-blue-100 bg-white/90 p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label className="text-xs font-bold text-slate-600">Minimum SparkScore<input type="range" min="0" max="100" value={minSpark} onChange={e=>setMinSpark(+e.target.value)} className="mt-3 w-full"/><span className="mt-1 block text-blue-600">{minSpark}+</span></label><label className="text-xs font-bold text-slate-600">Market-cap rank<input value={minRank} onChange={e=>setMinRank(Math.max(1,+e.target.value||1))} type="number" className="csl2-input mt-2"/><span className="text-[10px] text-slate-400">to</span><input value={maxRank} onChange={e=>setMaxRank(Math.max(1,+e.target.value||1))} type="number" className="csl2-input mt-1"/></label><label className="text-xs font-bold text-slate-600">Minimum confidence<input type="range" min="0" max="100" value={minConfidence} onChange={e=>setMinConfidence(+e.target.value)} className="mt-3 w-full"/><span className="mt-1 block text-blue-600">{minConfidence}%+</span></label><label className="text-xs font-bold text-slate-600">Minimum days in state<input type="range" min="0" max="90" value={minStreak} onChange={e=>setMinStreak(+e.target.value)} className="mt-3 w-full"/><span className="mt-1 block text-blue-600">{minStreak}+ days</span></label><label className="text-xs font-bold text-slate-600">Maximum absolute 24h move<input type="range" min="1" max="100" value={maxMove} onChange={e=>setMaxMove(+e.target.value)} className="mt-3 w-full"/><span className="mt-1 block text-blue-600">±{maxMove}%</span></label><label className="text-xs font-bold text-slate-600">Signal state<select value={regime} onChange={e=>setRegime(e.target.value)} className="csl2-input mt-2"><option value="all">All states</option><option value="calm">Calm</option><option value="building">Building</option><option value="awakening">Awakening</option><option value="volatile">Volatile</option></select></label><label className="text-xs font-bold text-slate-600">Sort results<select value={sort} onChange={e=>setSort(e.target.value as Sort)} className="csl2-input mt-2"><option value="spark">Highest SparkScore</option><option value="rank">Market-cap rank</option><option value="confidence">Highest confidence</option><option value="streak">Longest streak</option><option value="move">Largest 24h move</option></select></label><div className="flex items-end"><button onClick={reset} className="csl-btn-soft w-full">Reset filters</button></div></div></section>
 <div className="mt-5 flex flex-wrap items-center justify-between gap-3"><div><p className="csl-kicker">Matches</p><h2 className="mt-1 text-2xl font-black text-slate-950">{results.length} assets found</h2></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search within results…" className="csl2-search max-w-[320px]"/></div>
 <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{results.slice(0,120).map(c=>{const spark=getSparkScore(c),tier=getSignalTier(c),positive=c.change24hPct>=0;return <article key={c.id} className="rounded-[24px] border border-slate-100 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><Link href={`/coin/${c.id}`} className="flex min-w-0 items-center gap-3">{c.logoUrl?<img src={c.logoUrl} alt="" className="h-10 w-10 rounded-full"/>:<span className="h-10 w-10 rounded-full bg-slate-100"/>}<div className="min-w-0"><strong className="block truncate">{c.name}</strong><span className="text-[10px] font-bold uppercase text-slate-400">{c.symbol}{c.marketCapRank?` · #${c.marketCapRank}`:""}</span></div></Link><WatchlistButton coinId={c.id} compact/></div><div className="mt-4 flex items-end justify-between"><div><p className="text-lg font-black"><CurrencyAmount usd={c.price}/></p><p className={`text-[11px] font-bold ${positive?"text-emerald-600":"text-rose-600"}`}>{positive?"+":""}{c.change24hPct.toFixed(2)}%</p></div><div className="text-right"><p className="text-[9px] font-bold uppercase text-slate-400">SparkScore</p><p className="text-2xl font-black text-indigo-600">{spark.score}</p></div></div><div className="mt-3 grid grid-cols-3 gap-2 text-center"><div className="rounded-xl bg-slate-50 p-2"><span className="text-[9px] text-slate-400">State</span><b className="block text-[10px]">{TIER_CONFIG[tier].label}</b></div><div className="rounded-xl bg-slate-50 p-2"><span className="text-[9px] text-slate-400">Confidence</span><b className="block text-[10px]">{c.confidencePct.toFixed(0)}%</b></div><div className="rounded-xl bg-slate-50 p-2"><span className="text-[9px] text-slate-400">Streak</span><b className="block text-[10px]">{c.streakDays}d</b></div></div><div className="mt-3 grid grid-cols-2 gap-2"><Link href={`/coin/${c.id}`} className="csl-btn-soft !min-h-[36px] !text-[10px]">Research</Link><div className="[&>button]:min-h-[36px] [&>button]:w-full [&>button]:rounded-full [&>button]:border [&>button]:border-indigo-100 [&>button]:bg-white [&>button]:text-[10px] [&>button]:font-bold [&>button]:text-indigo-600"><AlertRuleButton coinId={c.id} compact/></div></div></article>})}</div>{results.length>120&&<p className="mt-5 text-center text-xs text-slate-400">Showing the first 120 matches. Tighten the filters to narrow the screen.</p>}<p className="mt-8 text-center text-[10px] leading-5 text-slate-400">The screener filters observable market data and CoinSparkLine model states. It does not predict future returns or recommend investments.</p></div>;
}
