"use client";
import {useMemo,useState} from "react";
import type {SparkHistoryPoint} from "@/lib/sparkHistory";

type Range=30|90|365;
function shortDate(value:string){return new Date(value).toLocaleDateString(undefined,{month:"short",day:"numeric"})}

export default function SparkHistoryChart({points}:{points:SparkHistoryPoint[]}){
 const[range,setRange]=useState<Range>(90);
 const data=useMemo(()=>points.slice(-range),[points,range]);
 const width=900,height=260,padX=22,padTop=20,padBottom=30;
 const coords=useMemo(()=>data.map((p,i)=>({x:data.length<=1?padX:padX+i*(width-padX*2)/(data.length-1),y:padTop+(100-p.score)*(height-padTop-padBottom)/100,p})),[data]);
 const path=coords.map((c,i)=>`${i?"L":"M"}${c.x.toFixed(1)} ${c.y.toFixed(1)}`).join(" ");
 const latest=data[data.length-1],first=data[0];const delta=latest&&first?latest.score-first.score:0;
 const high=data.length?Math.max(...data.map(p=>p.score)):0,low=data.length?Math.min(...data.map(p=>p.score)):0;
 const direction=delta>0?"rising":delta<0?"falling":"flat";const summary=`SparkScore ${range===365?"one year":`${range} day`} view. Latest ${latest?.score??"unavailable"}, range low ${low}, range high ${high}, direction ${direction}.`;
 return <div>
   <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-[10px] font-extrabold uppercase tracking-[.12em] text-slate-500">SparkScore history</p><div className="mt-2 flex items-end gap-3"><strong className="text-4xl font-black tracking-[-.06em] text-indigo-700">{latest?.score??"—"}</strong><span className={`pb-1 text-sm font-extrabold ${delta>0?"text-emerald-700":delta<0?"text-rose-700":"text-slate-500"}`}>{delta>0?"+":""}{delta} pts</span></div></div><div className="flex rounded-full border border-slate-200 bg-white p-1" role="group" aria-label="SparkScore history range">{([30,90,365] as Range[]).map(r=><button key={r} onClick={()=>setRange(r)} aria-pressed={range===r} className={`rounded-full px-3 py-1.5 text-[10px] font-extrabold transition ${range===r?"bg-slate-950 text-white":"text-slate-600 hover:text-indigo-700"}`}>{r===365?"1Y":`${r}D`}</button>)}</div></div>
   <p className="sr-only" aria-live="polite">{summary}</p>
   <div className="mt-5 overflow-hidden rounded-[22px] border border-indigo-100 bg-gradient-to-b from-indigo-50/55 to-white p-3 sm:p-4"><svg viewBox={`0 0 ${width} ${height}`} className="h-auto w-full" role="img" aria-label={summary}><defs><linearGradient id="sparkHistoryLine" x1="0" y1="0" x2="1" y2="0"><stop stopColor="#0e7490"/><stop offset=".5" stopColor="#4338ca"/><stop offset="1" stopColor="#6d28d9"/></linearGradient><linearGradient id="sparkHistoryFill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#4f46e5" stopOpacity=".18"/><stop offset="1" stopColor="#4f46e5" stopOpacity="0"/></linearGradient></defs>{[25,50,75].map(v=>{const y=padTop+(100-v)*(height-padTop-padBottom)/100;return <g key={v}><line x1={padX} x2={width-padX} y1={y} y2={y} stroke="#cbd5e1" strokeDasharray="4 8" opacity=".75"/><text x={padX} y={y-5} fontSize="10" fill="#64748b">{v}</text></g>})}{path&&<><path d={`${path} L ${coords[coords.length-1].x} ${height-padBottom} L ${coords[0].x} ${height-padBottom} Z`} fill="url(#sparkHistoryFill)"/><path d={path} fill="none" stroke="url(#sparkHistoryLine)" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/></>}{coords.filter((_,i)=>i===coords.length-1||i===0||i===Math.floor(coords.length/2)).map((c,i)=><circle key={i} cx={c.x} cy={c.y} r="5" fill="#fff" stroke="#4338ca" strokeWidth="3"/>)}{first&&<text x={padX} y={height-7} fontSize="10" fill="#64748b">{shortDate(first.date)}</text>}{latest&&<text x={width-padX} y={height-7} textAnchor="end" fontSize="10" fill="#64748b">{shortDate(latest.date)}</text>}</svg></div>
   <div className="mt-3 grid grid-cols-3 gap-2"><div className="rounded-2xl bg-slate-50 px-3 py-3"><span className="text-[9px] font-bold uppercase tracking-[.1em] text-slate-500">Range low</span><strong className="mt-1 block text-lg text-slate-900">{low}</strong></div><div className="rounded-2xl bg-slate-50 px-3 py-3"><span className="text-[9px] font-bold uppercase tracking-[.1em] text-slate-500">Range high</span><strong className="mt-1 block text-lg text-slate-900">{high}</strong></div><div className="rounded-2xl bg-slate-50 px-3 py-3"><span className="text-[9px] font-bold uppercase tracking-[.1em] text-slate-500">Direction</span><strong className={`mt-1 block text-lg ${delta>0?"text-emerald-700":delta<0?"text-rose-700":"text-slate-900"}`}>{delta>0?"Rising":delta<0?"Falling":"Flat"}</strong></div></div>
   <p className="mt-3 text-[10px] leading-5 text-slate-500">Historical values are reconstructed from the fitted regime model at each date. They show how today&apos;s SparkScore framework would describe past conditions; they are not archived predictions made on those dates.</p>
 </div>;
}
