"use client";

import Link from "next/link";
import {useMemo,useState} from "react";
import {Coin} from "@/types/coin";
import {getSignalTier} from "@/lib/tiers";
import {getSparkScore} from "@/lib/sparkScore";
import CurrencyAmount from "@/components/CurrencyAmount";
import TerminalChat from "@/components/TerminalChat";

type View="All"|"Moving now"|"Building"|"Volatile";
const stablecoins=new Set(["usdt","usdc","dai","busd","tusd","usdp"]);
const tierLabel={calm:"Calm",building:"Building",awakening:"Awakening",volatile:"Volatile"} as const;
function pct(v:number){return `${v>=0?"+":""}${v.toFixed(2)}%`}
function reason(coin:Coin){const tier=getSignalTier(coin),score=getSparkScore(coin).score;if(tier==="volatile")return score>=70?"Volatility is elevated and signal intensity remains high.":"Volatility is elevated, but the behavioural signal is less concentrated.";if(tier==="awakening")return"The model is leaning volatile while confidence is still forming.";if(tier==="building")return"Calm conditions are losing certainty and activity is building.";return"Behaviour remains comparatively stable with no strong transition pressure."}
function pattern(states:number[]|undefined){const values=states?.slice(-30)||[];return values.length?values:Array.from({length:30},(_,i)=>i>20?1:0)}

export default function TerminalLive({coins,updatedLabel}:{coins:Coin[];updatedLabel?:string}){
 const[view,setView]=useState<View>("All"),[selectedId,setSelectedId]=useState<string|null>(null),[chatOpen,setChatOpen]=useState(false);
 const eligible=useMemo(()=>coins.filter(c=>!stablecoins.has(c.symbol.toLowerCase())),[coins]);
 const ranked=useMemo(()=>[...eligible].sort((a,b)=>getSparkScore(b).score-getSparkScore(a).score),[eligible]);
 const selected=eligible.find(c=>c.id===selectedId)||ranked[0]||null;
 const filtered=useMemo(()=>ranked.filter(c=>{const tier=getSignalTier(c);if(view==="Moving now")return Math.abs(c.change24hPct)>=3||getSparkScore(c).score>=65;if(view==="Building")return tier==="building"||tier==="awakening";if(view==="Volatile")return tier==="volatile";return true}),[ranked,view]);
 const calm=eligible.filter(c=>getSignalTier(c)==="calm").length,building=eligible.filter(c=>getSignalTier(c)==="building").length,awakening=eligible.filter(c=>getSignalTier(c)==="awakening").length,volatile=eligible.filter(c=>getSignalTier(c)==="volatile").length;
 const avgScore=Math.round(eligible.reduce((sum,c)=>sum+getSparkScore(c).score,0)/Math.max(1,eligible.length));
 const unusual=eligible.filter(c=>getSparkScore(c).score>=70).length;
 const marketLabel=volatile>awakening+building?"The market is moving fast.":awakening+building>calm?"Something is changing.":"The market is selective.";
 const shelves=[{title:"Moving now",items:ranked.filter(c=>Math.abs(c.change24hPct)>=3||getSparkScore(c).score>=65).slice(0,8)},{title:"Pressure building",items:ranked.filter(c=>["building","awakening"].includes(getSignalTier(c))).slice(0,8)}];
 function selectBySymbol(symbol:string){const coin=eligible.find(c=>c.symbol.toUpperCase()===symbol.toUpperCase());if(coin){setSelectedId(coin.id);setChatOpen(false)}}
 return <main className="terminal-root terminal-v3">
  <header className="terminal-topbar"><Link href="/" className="terminal-brand">Coin<span>SparkLine</span></Link><nav aria-label="Main navigation"><a href="#live" data-active="true">Live</a><Link href="/opportunities">Radar</Link><Link href="/watchlist">My signals</Link></nav><div className="terminal-top-actions"><button type="button" onClick={()=>setChatOpen(true)} className="terminal-community-button">Community</button><Link href="/signin" className="terminal-signup">Sign up</Link></div></header>

  <section className="terminal-v3-hero" id="live"><span className="terminal-eyebrow">Live behavioural intelligence · {updatedLabel||"latest scan"}</span><h1>{marketLabel}</h1><p><strong>{unusual} markets</strong> are showing high-intensity behaviour right now. CoinSparkLine is watching changes in regime, confidence and volatility—not just price.</p><div className="terminal-v3-pulse"><div><span>Market Spark</span><strong>{avgScore}</strong></div><div><span>Building</span><strong>{building+awakening}</strong></div><div><span>Volatile</span><strong>{volatile}</strong></div><div><span>Calm</span><strong>{calm}</strong></div></div></section>

  <section className="terminal-v3-discovery" aria-label="Markets worth a look"><div className="terminal-v3-discovery-head"><div><span className="terminal-eyebrow">Worth a look</span><h2>Start with what&apos;s changing.</h2></div><div className="terminal-v2-segments">{(["All","Moving now","Building","Volatile"] as View[]).map(item=><button key={item} data-active={view===item} onClick={()=>setView(item)}>{item}</button>)}</div></div><div className="terminal-v3-rail">{filtered.slice(0,10).map((c,index)=>{const spark=getSparkScore(c).score;return <button key={c.id} onClick={()=>setSelectedId(c.id)} data-active={selected?.id===c.id}><span className="terminal-v3-rank">{String(index+1).padStart(2,"0")}</span>{c.logoUrl?<img src={c.logoUrl} alt=""/>:null}<div><strong>{c.symbol.toUpperCase()}</strong><small>{tierLabel[getSignalTier(c)]}</small></div><em>{spark}</em><i data-direction={c.change24hPct>=0?"up":"down"}>{pct(c.change24hPct)}</i></button>})}</div></section>

  {selected&&<section className="terminal-v3-story"><div className="terminal-v3-story-copy"><span className="terminal-eyebrow">Now moving</span><div className="terminal-v3-title">{selected.logoUrl?<img src={selected.logoUrl} alt=""/>:null}<div><small>{selected.symbol.toUpperCase()}</small><h2>{selected.name}</h2></div></div><h3>{getSparkScore(selected).score}</h3><span className="terminal-v3-score-label">SparkScore · {tierLabel[getSignalTier(selected)]}</span><p>{reason(selected)}</p><div className="terminal-v3-actions"><Link href={`/coin/${selected.id}`}>Understand why</Link><Link href="/signin">Watch this signal</Link><button type="button" onClick={()=>setChatOpen(true)}>Discuss ${selected.symbol.toUpperCase()}</button></div></div><div className="terminal-v3-visual"><div className="terminal-v3-chart-head"><span>Behaviour · last 30 observations</span><strong>{selected.confidencePct.toFixed(0)}% confidence</strong></div><div className="terminal-v3-behaviour-chart">{pattern(selected.recentStates).map((state,i)=><i key={i} data-state={state} style={{height:`${20+((i*13)%34)+(state?34:0)}%`}}><span/></i>)}</div><div className="terminal-v3-chart-axis"><span>Calm</span><span>Transition pressure</span><span>Volatile</span></div><dl><div><dt>Price</dt><dd><CurrencyAmount usd={selected.price}/></dd></div><div><dt>24h</dt><dd data-direction={selected.change24hPct>=0?"up":"down"}>{pct(selected.change24hPct)}</dd></div><div><dt>Current streak</dt><dd>{selected.streakDays}d</dd></div><div><dt>Typical flip</dt><dd>{selected.medianDaysToFlip>365?"Beyond horizon":`${selected.medianDaysToFlip.toFixed(1)}d`}</dd></div></dl></div></section>}

  <section className="terminal-v3-shelves">{shelves.map(shelf=>shelf.items.length?<div key={shelf.title}><div className="terminal-v3-shelf-head"><h2>{shelf.title}</h2><span>{shelf.items.length} signals</span></div><div className="terminal-v3-cards">{shelf.items.map(c=><button key={c.id} onClick={()=>setSelectedId(c.id)}><div><strong>{c.symbol.toUpperCase()}</strong><span>{c.name}</span></div><em>{getSparkScore(c).score}</em><small>{tierLabel[getSignalTier(c)]}</small></button>)}</div></div>:null)}</section>

  <section className="terminal-v3-conversion"><span className="terminal-eyebrow">Make it yours</span><h2>Want CoinSparkLine to keep watching?</h2><p>Save the markets you care about and build alerts around behavioural changes instead of staring at price all day.</p><div><Link href="/signup">Create free account</Link><Link href="/methodology">See how SparkScore works</Link></div></section>

  {selected&&<div className="terminal-v2-nowbar"><button onClick={()=>setSelectedId(selected.id)}><span>NOW MOVING</span>{selected.logoUrl?<img src={selected.logoUrl} alt=""/>:null}<strong>{selected.symbol.toUpperCase()}</strong><em>{getSparkScore(selected).score}</em><small>{tierLabel[getSignalTier(selected)]}</small><b data-direction={selected.change24hPct>=0?"up":"down"}>{pct(selected.change24hPct)}</b></button><div><button type="button" onClick={()=>{const i=Math.max(0,ranked.findIndex(c=>c.id===selected.id));setSelectedId(ranked[(i-1+ranked.length)%ranked.length]?.id||selected.id)}} aria-label="Previous signal">←</button><button type="button" onClick={()=>{const i=Math.max(0,ranked.findIndex(c=>c.id===selected.id));setSelectedId(ranked[(i+1)%ranked.length]?.id||selected.id)}} aria-label="Next signal">→</button><button type="button" onClick={()=>setChatOpen(true)}>Community</button></div></div>}

  <div className="terminal-v2-chat-drawer" data-open={chatOpen} aria-hidden={!chatOpen}><button className="terminal-v2-chat-backdrop" onClick={()=>setChatOpen(false)} aria-label="Close community"/><div className="terminal-v2-chat-panel"><div className="terminal-v2-chat-panel-head"><div><span className="terminal-eyebrow">Community</span><strong>{selected?`Discussing $${selected.symbol.toUpperCase()}`:"Live market discussion"}</strong></div><button type="button" onClick={()=>setChatOpen(false)} aria-label="Close community">×</button></div><TerminalChat selectedSymbol={selected?.symbol} onSelect={selectBySymbol}/></div></div>
 </main>;
}
