"use client";

import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import type {RealtimeChannel} from "@supabase/supabase-js";
import {getSupabaseBrowserClient} from "@/lib/supabaseClient";

type ChatMessage={id:string;user_id:string;display_name:string;body:string;coin_symbol:string|null;created_at:string};
type SystemEvent={id:string;symbol:string;title:string;body:string;importance:number;created_at:string};
type TimelineItem={kind:"message";at:string;message:ChatMessage}|{kind:"event";at:string;event:SystemEvent};
type State="connecting"|"live"|"degraded";
function initials(value:string){return value.trim().slice(0,2).toUpperCase()||"CS"}
function time(value:string){return new Date(value).toLocaleTimeString(undefined,{hour:"2-digit",minute:"2-digit"})}
function appendUnique(items:ChatMessage[],message:ChatMessage){return items.some(x=>x.id===message.id)?items:[...items.slice(-39),message]}

export default function TerminalChat({selectedSymbol,selectedScore,selectedRegime,selectedChange,onSelect}:{selectedSymbol?:string|null;selectedScore?:number|null;selectedRegime?:string|null;selectedChange?:number|null;onSelect?:(symbol:string)=>void}){
 const[messages,setMessages]=useState<ChatMessage[]>([]),[systemEvents,setSystemEvents]=useState<SystemEvent[]>([]),[body,setBody]=useState(""),[userId,setUserId]=useState<string|null>(null),[displayName,setDisplayName]=useState("Member"),[state,setState]=useState<State>("connecting"),[sending,setSending]=useState(false),[error,setError]=useState<string|null>(null);const endRef=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{let mounted=true;let channel:RealtimeChannel|null=null;const supabase=getSupabaseBrowserClient();async function boot(){try{const{data:auth}=await supabase.auth.getUser();if(!mounted)return;if(auth.user){setUserId(auth.user.id);const meta=auth.user.user_metadata||{};setDisplayName(String(meta.display_name||meta.full_name||auth.user.email?.split("@")[0]||"Member"))}const{data,error}=await supabase.from("community_messages").select("id,user_id,display_name,body,coin_symbol,created_at").order("created_at",{ascending:false}).limit(30);if(!mounted)return;if(error)throw error;setMessages(((data||[]) as ChatMessage[]).reverse());channel=supabase.channel("terminal-community").on("postgres_changes",{event:"INSERT",schema:"public",table:"community_messages"},payload=>setMessages(items=>appendUnique(items,payload.new as ChatMessage))).subscribe(status=>{if(!mounted)return;if(status==="SUBSCRIBED")setState("live");else if(status==="CHANNEL_ERROR"||status==="TIMED_OUT"||status==="CLOSED")setState("degraded");else setState("connecting")})}catch{if(mounted)setState("degraded")}}void boot();return()=>{mounted=false;if(channel)void supabase.removeChannel(channel)}},[]);
 useEffect(()=>{let mounted=true;async function loadEvents(){try{const response=await fetch("/api/intelligence-events",{cache:"no-store"});if(!response.ok)return;const result=await response.json();if(mounted)setSystemEvents((Array.isArray(result.events)?result.events:[]).slice(0,12))}catch{}}void loadEvents();const timer=window.setInterval(loadEvents,30000);return()=>{mounted=false;window.clearInterval(timer)}},[]);
 const selected=selectedSymbol?.toUpperCase()||null;const timeline=useMemo<TimelineItem[]>(()=>{const userItems:TimelineItem[]=messages.slice(-16).map(message=>({kind:"message",at:message.created_at,message}));const eventItems:TimelineItem[]=systemEvents.slice(0,7).map(event=>({kind:"event",at:event.created_at,event}));return [...userItems,...eventItems].sort((a,b)=>new Date(a.at).getTime()-new Date(b.at).getTime()).slice(-22)},[messages,systemEvents]);
 useEffect(()=>{endRef.current?.scrollIntoView({block:"nearest"})},[timeline.length]);
 function render(text:string){return text.split(/(\$[A-Za-z0-9]{2,10})/g).map((part,i)=>/^\$[A-Za-z0-9]{2,10}$/.test(part)?<button key={i} type="button" className="terminal-tag" onClick={()=>onSelect?.(part.slice(1).toUpperCase())}>{part.toUpperCase()}</button>:<span key={i}>{part}</span>)}
 async function send(e:FormEvent){e.preventDefault();const text=body.trim();if(!text||!userId||sending)return;setSending(true);setError(null);const symbol=text.match(/\$([A-Za-z0-9]{2,10})/)?.[1]?.toUpperCase()||selected;const{data,error}=await (getSupabaseBrowserClient().from("community_messages") as any).insert({user_id:userId,display_name:displayName.slice(0,40),body:text.slice(0,500),coin_symbol:symbol}).select("id,user_id,display_name,body,coin_symbol,created_at").single();if(error)setError("Message could not be sent.");else{if(data)setMessages(items=>appendUnique(items,data as ChatMessage));setBody("")}setSending(false)}
 return <section className="terminal-panel terminal-chat" aria-label="Live community"><header className="terminal-panel-head"><div><span className="terminal-eyebrow">Community + intelligence</span><h2>Live room</h2></div><span className="terminal-status" data-state={state}>{state==="live"?"Connected":state==="connecting"?"Connecting":"Degraded"}</span></header>{selected?<div className="terminal-chat-signal"><button type="button" onClick={()=>onSelect?.(selected)}><span>FOCUS</span><strong>${selected}</strong></button><div><span>SPARK</span><strong>{selectedScore??"—"}</strong></div><div><span>REGIME</span><strong>{selectedRegime||"—"}</strong></div><div><span>24H</span><strong data-direction={(selectedChange??0)>=0?"up":"down"}>{selectedChange==null?"—":`${selectedChange>=0?"+":""}${selectedChange.toFixed(2)}%`}</strong></div></div>:<div className="terminal-chat-context">Global market conversation</div>}<div className="terminal-messages">{state==="degraded"&&messages.length===0?<div className="terminal-empty">Community is temporarily unavailable. Intelligence events can still appear.</div>:null}{timeline.length===0&&state!=="degraded"?<div className="terminal-empty">The room is open. Real model changes will appear between community messages.</div>:null}{timeline.map(item=>item.kind==="event"?<article key={`e-${item.event.id}`} className="terminal-system-event"><div className="terminal-system-mark">CS</div><div><div className="terminal-message-meta"><strong>CoinSparkLine</strong><time>{time(item.event.created_at)}</time></div><button type="button" onClick={()=>onSelect?.(item.event.symbol)}><b>${item.event.symbol}</b> {item.event.title.replace(`${item.event.symbol} `,"")}</button><p>{item.event.body}</p></div></article>:<article key={`m-${item.message.id}`} className="terminal-message" data-mine={item.message.user_id===userId}><div className="terminal-avatar">{initials(item.message.display_name)}</div><div><div className="terminal-message-meta"><strong>{item.message.display_name}</strong><time>{time(item.message.created_at)}</time></div><p>{render(item.message.body)}</p>{item.message.coin_symbol?<button type="button" className="terminal-message-asset" onClick={()=>onSelect?.(item.message.coin_symbol!)}>${item.message.coin_symbol}</button>:null}</div></article>)}<div ref={endRef}/></div>{userId?<form onSubmit={send} className="terminal-composer"><label htmlFor="terminal-message" className="sr-only">Message the live room</label><textarea id="terminal-message" rows={2} value={body} onChange={e=>setBody(e.target.value)} maxLength={500} placeholder={selected?`Talk about $${selected}…`:"Share what you are watching…"}/><div><span>Use $TICKER to link a market</span><button type="submit" disabled={!body.trim()||sending}>{sending?"Sending…":"Send"}</button></div>{error?<p role="alert">{error}</p>:null}</form>:<div className="terminal-chat-signin"><span>Sign in to join the live room.</span><a href="/signin">Sign in</a></div>}</section>
}
