"use client";

import Link from "next/link";
import {useMemo,useState} from "react";
import {Coin} from "@/types/coin";
import {getSignalTier} from "@/lib/tiers";
import {getSparkScore} from "@/lib/sparkScore";
import CurrencyAmount from "@/components/CurrencyAmount";
import TerminalChat from "@/components/TerminalChat";

type View="All"|"Moving now"|"Building"|"Volatile";
const stablecoins=new Set(["usdt","usdc","dai","busd","tusd","usdp"]);
const tierLabel={calm:"Calm",building:"Building",awakening:"Awakening",volatile:"Volatile"} as const;
function pct(v:number){return `${v>=0?"+":""}${v.toFixed(2)}%`}
function reason(coin:Coin){const tier=getSignalTier(coin),score=getSparkScore(coin).score;if(tier==="volatile")return score>=70?"Volatility is elevated and signal intensity remains high.":"Volatility is elevated, but the behavioural signal is less concentrated.";if(tier==="awakening")return"The model is leaning volatile while confidence is still forming.";if(tier==="building")return"Calm conditions are losing certainty and activity is building.";return"Behaviour remains comparatively stable with no strong transition pressure."}
function miniPath(states:number[]|undefined){const values=states?.slice(-22)||[];return values.length?values:Array.from({length:22},()=>0)}

export default function TerminalLive({coins,updatedLabel}:{coins:Coin[];updatedLabel?:string}){
 const[view,setView]=useState<View>("All"),[selectedId,setSelectedId]=useState<string|null>(null),[chatOpen,setChatOpen]=useState(false);
 const eligible=useMemo(()=>coins.filter(c=>!stablecoins.has(c.symbol.toLowerCase())),[coins]);
 const ranked=useMemo(()=>[...eligible].sort((a,b)=>getSparkScore(b).score-getSparkScore(a).score),[eligible]);
 const selected=eligible.find(c=>c.id===selectedId)||ranked[0]||null;
 const filtered=useMemo(()=>ranked.filter(c=>{const tier=getSignalTier(c);if(view==="Moving now")return Math.abs(c.change24hPct)>=3||getSparkScore(c).score>=65;if(view==="Building")return tier==="building"||tier==="awakening";if(view==="Volatile")return tier==="volatile";return true}),[ranked,view]);
 const calm=eligible.filter(c=>getSignalTier(c)==="calm").length,building=eligible.filter(c=>getSignalTier(c)==="building").length,awakening=eligible.filter(c=>getSignalTier(c)==="awakening").length,volatile=eligible.filter(c=>getSignalTier(c)==="volatile").length;
 const avgScore=Math.round(eligible.reduce((sum,c)=>sum+getSparkScore(c).score,0)/Math.max(1,eligible.length));
 const unusual=eligible.filter(c=>getSparkScore(c).score>=70).length;
 const marketLabel=volatile>awakening+building?"Markets are moving fast.":awakening+building>calm?"Markets are waking up.":"Markets are selective.";
 const detections=ranked.slice(0,6);
 const shelves=[
  {title:"Moving now",items:ranked.filter(c=>Math.abs(c.change24hPct)>=3||getSparkScore(c).score>=65).slice(0,8)},
  {title:"Building pressure",items:ranked.filter(c=>["building","awakening"].includes(getSignalTier(c))).slice(0,8)},
  {title:"Highest SparkScore",items:ranked.slice(0,8)},
 ];
 function selectBySymbol(symbol:string){const coin=eligible.find(c=>c.symbol.toUpperCase()===symbol.toUpperCase());if(coin){setSelectedId(coin.id);setChatOpen(false)}}
 return <main className="terminal-root terminal-v2">
  <header className="terminal-topbar"><Link href="/" className="terminal-brand">Coin<span>SparkLine</span></Link><nav aria-label="Terminal navigation"><a href="#live" data-active="true">LIVE</a><Link href="/opportunities">RADAR</Link><Link href="/watchlist">MY SIGNALS</Link></nav><div className="terminal-top-actions"><button type="button" onClick={()=>setChatOpen(true)} className="terminal-community-button">Community</button><Link href="/methodology">Methodology</Link></div></header>

  <section className="terminal-v2-hero" id="live"><div className="terminal-v2-hero-copy"><span className="terminal-eyebrow">Live behavioural intelligence</span><h1>{marketLabel}</h1><p><b>{unusual} assets</b> are showing high-intensity behaviour across the current scan. Spark pressure is <strong>{avgScore}</strong>.</p><div className="terminal-v2-pills"><span>{updatedLabel||"Latest market snapshot"}</span><span>{volatile} volatile</span><span>{building+awakening} building / awakening</span></div></div>{selected&&<button className="terminal-v2-now-card" onClick={()=>setSelectedId(selected.id)}><span>NOW MOVING</span><div><strong>{selected.symbol.toUpperCase()}</strong><em>{getSparkScore(selected).score}</em></div><small>{tierLabel[getSignalTier(selected)]} · {pct(selected.change24hPct)}</small></button>}</section>

  <div className="terminal-v2-ticker" aria-label="Market ticker">{ranked.slice(0,12).map(c=><button key={c.id} onClick={()=>setSelectedId(c.id)} data-active={selected?.id===c.id}><b>{c.symbol.toUpperCase()}</b><span><CurrencyAmount usd={c.price}/></span><em data-direction={c.change24hPct>=0?"up":"down"}>{pct(c.change24hPct)}</em><i>SPK {getSparkScore(c).score}</i></button>)}</div>

  {selected&&<section className="terminal-v2-focus"><div className="terminal-v2-focus-copy"><span className="terminal-eyebrow">What&apos;s happening</span><div className="terminal-v2-asset-title">{selected.logoUrl?<img src={selected.logoUrl} alt=""/>:null}<div><span>{selected.symbol.toUpperCase()}</span><h2>{selected.name}</h2></div></div><p>{reason(selected)}</p><div className="terminal-v2-focus-actions"><Link href={`/coin/${selected.id}`}>Open research</Link><Link href={`/compare?coins=${encodeURIComponent(selected.id)}`}>Compare</Link><Link href="/alerts">Alert me</Link></div></div><div className="terminal-v2-score"><span>SPARKSCORE</span><strong>{getSparkScore(selected).score}</strong><small>{tierLabel[getSignalTier(selected)]} · {selected.confidencePct.toFixed(0)}% confidence</small></div><div className="terminal-v2-chart" aria-label={`${selected.name} recent regime pattern`}>{miniPath(selected.recentStates).map((state,i)=><i key={i} data-state={state} style={{height:`${state?46:18+(i%5)*3}%`}}/>)}</div><dl className="terminal-v2-facts"><div><dt>Price</dt><dd><CurrencyAmount usd={selected.price}/></dd></div><div><dt>24H</dt><dd data-direction={selected.change24hPct>=0?"up":"down"}>{pct(selected.change24hPct)}</dd></div><div><dt>Regime streak</dt><dd>{selected.streakDays}d</dd></div><div><dt>Typical flip</dt><dd>{selected.medianDaysToFlip>365?">365d":`${selected.medianDaysToFlip.toFixed(1)}d`}</dd></div></dl></section>}

  <section className="terminal-v2-library"><header><div><span className="terminal-eyebrow">Explore the market</span><h2>What deserves attention?</h2></div><div className="terminal-v2-segments" role="group" aria-label="Market filter">{(["All","Moving now","Building","Volatile"] as View[]).map(item=><button key={item} data-active={view===item} onClick={()=>setView(item)}>{item}</button>)}</div></header>{shelves.map(shelf=>{const items=view==="All"?shelf.items:filtered.slice(0,8);if(!items.length)return null;return <div className="terminal-v2-shelf" key={shelf.title}><div className="terminal-v2-shelf-title"><h3>{view==="All"?shelf.title:view}</h3><span>{items.length} assets</span></div><div className="terminal-v2-cards">{items.map(c=>{const tier=getSignalTier(c),spark=getSparkScore(c).score;return <button key={c.id} onClick={()=>setSelectedId(c.id)} data-active={selected?.id===c.id} className="terminal-v2-card">{c.logoUrl?<img src={c.logoUrl} alt=""/>:null}<div className="terminal-v2-card-top"><strong>{c.symbol.toUpperCase()}</strong><em>{spark}</em></div><span>{c.name}</span><small>{tierLabel[tier]}</small><div className="terminal-v2-card-bottom"><b><CurrencyAmount usd={c.price}/></b><i data-direction={c.change24hPct>=0?"up":"down"}>{pct(c.change24hPct)}</i></div></button>})}</div></div>})}</section>

  <section className="terminal-v2-lower"><div className="terminal-v2-feed"><div className="terminal-v2-section-title"><span className="terminal-eyebrow">Live intelligence</span><h2>Current detections</h2><p>Real readings from the latest scan. No fabricated activity.</p></div>{detections.map(c=><button key={c.id} onClick={()=>setSelectedId(c.id)}><span className="terminal-v2-feed-score">{getSparkScore(c).score}</span><div><strong>${c.symbol.toUpperCase()}</strong><p>{reason(c)}</p></div><span className="terminal-v2-feed-regime">{tierLabel[getSignalTier(c)]}</span></button>)}</div><div className="terminal-v2-regimes"><div className="terminal-v2-section-title"><span className="terminal-eyebrow">Market structure</span><h2>Regime mix</h2></div>{[["Calm",calm,"calm"],["Building",building,"building"],["Awakening",awakening,"awakening"],["Volatile",volatile,"volatile"]].map(([label,value,key])=>{const count=Number(value);return <div className="terminal-v2-regime-row" key={String(label)}><div><span>{label}</span><strong>{count}</strong></div><div><i data-regime={key} style={{width:`${Math.max(4,(count/Math.max(1,eligible.length))*100)}%`}}/></div></div>})}<button type="button" className="terminal-v2-community-cta" onClick={()=>setChatOpen(true)}><span>COMMUNITY</span><strong>Open live discussion →</strong><small>Discuss the signals without leaving the market.</small></button></div></section>

  {selected&&<div className="terminal-v2-nowbar"><button onClick={()=>setSelectedId(selected.id)}><span>NOW MOVING</span>{selected.logoUrl?<img src={selected.logoUrl} alt=""/>:null}<strong>{selected.symbol.toUpperCase()}</strong><em>{getSparkScore(selected).score}</em><small>{tierLabel[getSignalTier(selected)]}</small><b data-direction={selected.change24hPct>=0?"up":"down"}>{pct(selected.change24hPct)}</b></button><div><button type="button" onClick={()=>{const i=Math.max(0,ranked.findIndex(c=>c.id===selected.id));setSelectedId(ranked[(i-1+ranked.length)%ranked.length]?.id||selected.id)}} aria-label="Previous signal">←</button><button type="button" onClick={()=>{const i=Math.max(0,ranked.findIndex(c=>c.id===selected.id));setSelectedId(ranked[(i+1)%ranked.length]?.id||selected.id)}} aria-label="Next signal">→</button><button type="button" onClick={()=>setChatOpen(true)}>Community</button></div></div>}

  <div className="terminal-v2-chat-drawer" data-open={chatOpen} aria-hidden={!chatOpen}><button className="terminal-v2-chat-backdrop" onClick={()=>setChatOpen(false)} aria-label="Close community"/><div className="terminal-v2-chat-panel"><div className="terminal-v2-chat-panel-head"><div><span className="terminal-eyebrow">Community</span><strong>{selected?`Discussing $${selected.symbol.toUpperCase()}`:"Live market discussion"}</strong></div><button type="button" onClick={()=>setChatOpen(false)} aria-label="Close community">×</button></div><TerminalChat selectedSymbol={selected?.symbol} onSelect={selectBySymbol}/></div></div>
 </main>;
}
