"use client";

import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import type {RealtimeChannel} from "@supabase/supabase-js";
import {getSupabaseBrowserClient} from "@/lib/supabaseClient";

type ChatMessage={id:string;user_id:string;display_name:string;body:string;coin_symbol:string|null;created_at:string};
type State="connecting"|"live"|"degraded";
function initials(value:string){return value.trim().slice(0,2).toUpperCase()||"CS"}
function time(value:string){return new Date(value).toLocaleTimeString(undefined,{hour:"2-digit",minute:"2-digit"})}
function appendUnique(items:ChatMessage[],message:ChatMessage){return items.some(x=>x.id===message.id)?items:[...items.slice(-39),message]}

export default function TerminalChat({selectedSymbol,onSelect}:{selectedSymbol?:string|null;onSelect?:(symbol:string)=>void}){
 const[messages,setMessages]=useState<ChatMessage[]>([]),[body,setBody]=useState(""),[userId,setUserId]=useState<string|null>(null),[displayName,setDisplayName]=useState("Member"),[state,setState]=useState<State>("connecting"),[sending,setSending]=useState(false),[error,setError]=useState<string|null>(null);const endRef=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{let mounted=true;let channel:RealtimeChannel|null=null;const supabase=getSupabaseBrowserClient();async function boot(){try{const{data:auth}=await supabase.auth.getUser();if(!mounted)return;if(auth.user){setUserId(auth.user.id);const meta=auth.user.user_metadata||{};setDisplayName(String(meta.display_name||meta.full_name||auth.user.email?.split("@")[0]||"Member"))}const{data,error}=await supabase.from("community_messages").select("id,user_id,display_name,body,coin_symbol,created_at").order("created_at",{ascending:false}).limit(30);if(!mounted)return;if(error)throw error;setMessages(((data||[]) as ChatMessage[]).reverse());channel=supabase.channel("terminal-community").on("postgres_changes",{event:"INSERT",schema:"public",table:"community_messages"},payload=>setMessages(items=>appendUnique(items,payload.new as ChatMessage))).subscribe(status=>{if(!mounted)return;if(status==="SUBSCRIBED")setState("live");else if(status==="CHANNEL_ERROR"||status==="TIMED_OUT"||status==="CLOSED")setState("degraded");else setState("connecting")})}catch{if(mounted)setState("degraded")}}void boot();return()=>{mounted=false;if(channel)void supabase.removeChannel(channel)}},[]);
 useEffect(()=>{endRef.current?.scrollIntoView({block:"nearest"})},[messages.length]);
 const selected=selectedSymbol?.toUpperCase()||null;const relevant=useMemo(()=>messages.slice(-18),[messages]);
 function render(text:string){return text.split(/(\$[A-Za-z0-9]{2,10})/g).map((part,i)=>/^\$[A-Za-z0-9]{2,10}$/.test(part)?<button key={i} type="button" className="terminal-tag" onClick={()=>onSelect?.(part.slice(1).toUpperCase())}>{part.toUpperCase()}</button>:<span key={i}>{part}</span>)}
 async function send(e:FormEvent){e.preventDefault();const text=body.trim();if(!text||!userId||sending)return;setSending(true);setError(null);const symbol=text.match(/\$([A-Za-z0-9]{2,10})/)?.[1]?.toUpperCase()||selected;const{data,error}=await (getSupabaseBrowserClient().from("community_messages") as any).insert({user_id:userId,display_name:displayName.slice(0,40),body:text.slice(0,500),coin_symbol:symbol}).select("id,user_id,display_name,body,coin_symbol,created_at").single();if(error)setError("Message could not be sent.");else{if(data)setMessages(items=>appendUnique(items,data as ChatMessage));setBody("")}setSending(false)}
 return <section className="terminal-panel terminal-chat" aria-label="Live community"><header className="terminal-panel-head"><div><span className="terminal-eyebrow">Community</span><h2>Live room</h2></div><span className="terminal-status" data-state={state}>{state==="live"?"Connected":state==="connecting"?"Connecting":"Degraded"}</span></header><div className="terminal-chat-context">{selected?<>Focused on <button type="button" onClick={()=>onSelect?.(selected)}>${selected}</button></>:"Global market conversation"}</div><div className="terminal-messages">{state==="degraded"&&messages.length===0?<div className="terminal-empty">Community is temporarily unavailable.</div>:null}{relevant.length===0&&state!=="degraded"?<div className="terminal-empty">The room is open. Market references such as <b>$BTC</b> become interactive.</div>:null}{relevant.map(m=><article key={m.id} className="terminal-message" data-mine={m.user_id===userId}><div className="terminal-avatar">{initials(m.display_name)}</div><div><div className="terminal-message-meta"><strong>{m.display_name}</strong><time>{time(m.created_at)}</time></div><p>{render(m.body)}</p>{m.coin_symbol?<button type="button" className="terminal-message-asset" onClick={()=>onSelect?.(m.coin_symbol!)}>${m.coin_symbol}</button>:null}</div></article>)}<div ref={endRef}/></div>{userId?<form onSubmit={send} className="terminal-composer"><label htmlFor="terminal-message" className="sr-only">Message the live room</label><textarea id="terminal-message" rows={2} value={body} onChange={e=>setBody(e.target.value)} maxLength={500} placeholder={selected?`Talk about $${selected}…`:"Share what you are watching…"}/><div><span>Use $TICKER to link a market</span><button type="submit" disabled={!body.trim()||sending}>{sending?"Sending…":"Send"}</button></div>{error?<p role="alert">{error}</p>:null}</form>:<div className="terminal-chat-signin"><span>Sign in to join the live room.</span><a href="/signin">Sign in</a></div>}</section>
}
