import {unstable_cache} from "next/cache";
const MARKETS_URL="https://api.coingecko.com/api/v3/coins/markets";const CHART_URL=(id:string)=>`https://api.coingecko.com/api/v3/coins/${id}/market_chart`;const DETAIL_URL=(id:string)=>`https://api.coingecko.com/api/v3/coins/${id}`;const SEARCH_URL="https://api.coingecko.com/api/v3/search";
export interface CoinMeta{id:string;symbol:string;name:string;market_cap_rank:number|null;current_price:number;image:string;price_change_percentage_24h:number|null;price_change_percentage_7d_in_currency?:number|null;market_cap:number|null;ath:number|null;ath_date:string|null;circulating_supply:number|null;total_supply:number|null;max_supply:number|null}
function apiHeaders(apiKey?:string):HeadersInit{return apiKey?{"x-cg-demo-api-key":apiKey}:{}}
async function fetchWithRetry(url:string,apiKey?:string,maxRetries=2,baseWait=1200):Promise<Response>{let last="";for(let attempt=0;attempt<=maxRetries;attempt++){try{const resp=await fetch(url,{headers:apiHeaders(apiKey),signal:AbortSignal.timeout(12000)});if(resp.status!==429&&resp.status<500){if(!resp.ok)throw new Error(`HTTP ${resp.status}`);return resp}last=`HTTP ${resp.status}`;if(attempt<maxRetries){const retryAfter=resp.headers.get("Retry-After");const wait=retryAfter?Math.min(parseFloat(retryAfter)*1000,8000):baseWait*2**attempt;await new Promise(r=>setTimeout(r,wait))}}catch(e){last=e instanceof Error?e.message:String(e);if(attempt<maxRetries)await new Promise(r=>setTimeout(r,baseWait*2**attempt))}}throw new Error(`Market data unavailable after retries: ${last}`)}
async function topCoinsRaw(n:number,apiKey?:string){const coins:CoinMeta[]=[];for(let page=1;page<=Math.ceil(n/100);page++){const params=new URLSearchParams({vs_currency:"usd",order:"market_cap_desc",per_page:String(Math.min(100,n-coins.length)),page:String(page),sparkline:"false",price_change_percentage:"7d"});const r=await fetchWithRetry(`${MARKETS_URL}?${params}`,apiKey);coins.push(...await r.json());if(coins.length>=n)break}return coins.slice(0,n)}
export async function fetchTopCoins(n:number,apiKey?:string):Promise<CoinMeta[]>{if(apiKey)return topCoinsRaw(n,apiKey);return unstable_cache(()=>topCoinsRaw(n),[`cg-top-${n}`],{revalidate:300,tags:["market-data"]})()}
async function priceHistoryRaw(coinId:string,days:number,apiKey?:string,maxRetries=2){const params=new URLSearchParams({vs_currency:"usd",days:String(days)});const r=await fetchWithRetry(`${CHART_URL(coinId)}?${params}`,apiKey,maxRetries);const data=await r.json();return ((data.prices||[]) as [number,number][]).map(([ts,close])=>({date:new Date(ts).toISOString(),close}))}
export async function fetchPriceHistory(coinId:string,days:number,apiKey?:string,maxRetries=2):Promise<{date:string;close:number}[]>{if(apiKey)return priceHistoryRaw(coinId,days,apiKey,maxRetries);return unstable_cache(()=>priceHistoryRaw(coinId,days,undefined,maxRetries),[`cg-history-${coinId}-${days}`],{revalidate:1800,tags:[`coin-${coinId}`,"price-history"]})()}
export interface PurchaseMarket{name:string;pair:string;url:string|null}export interface CoinDetails{symbol:string;description:string;homepage:string|null;imageUrl:string|null;currentPrice:number|null;marketCap:number|null;ath:number|null;athDate:string|null;circulatingSupply:number|null;totalSupply:number|null;maxSupply:number|null;platforms:string[];purchaseMarkets:PurchaseMarket[]}
async function coinDetailsRaw(coinId:string,apiKey?:string):Promise<CoinDetails|null>{try{const params=new URLSearchParams({localization:"false",tickers:"true",community_data:"false",developer_data:"false",sparkline:"false",market_data:"true"});const r=await fetchWithRetry(`${DETAIL_URL(coinId)}?${params}`,apiKey),data=await r.json(),md=data.market_data||{};let description:string=data.description?.en||"";if(description.length>600){const cut=description.slice(0,600);description=cut.slice(0,cut.lastIndexOf(".")+1)||cut}const homepage=(data.links?.homepage||[]).find((h:string)=>h)||null,tickerRows=Array.isArray(data.tickers)?data.tickers:[],seen=new Set<string>();const purchaseMarkets:PurchaseMarket[]=tickerRows.filter((t:any)=>!t?.is_anomaly&&!t?.is_stale&&t?.market?.name).sort((a:any,b:any)=>(b?.converted_volume?.usd||0)-(a?.converted_volume?.usd||0)).reduce((acc:PurchaseMarket[],t:any)=>{const name=String(t.market.name);if(seen.has(name)||acc.length>=6)return acc;seen.add(name);acc.push({name,pair:`${String(t.base||data.symbol||"").toUpperCase()}/${String(t.target||"").toUpperCase()}`,url:typeof t.trade_url==="string"&&t.trade_url.startsWith("http")?t.trade_url:null});return acc},[]);return{symbol:(data.symbol||coinId.slice(0,5)).toUpperCase(),description,homepage,imageUrl:data.image?.large||data.image?.small||null,currentPrice:md.current_price?.usd??null,marketCap:md.market_cap?.usd??null,ath:md.ath?.usd??null,athDate:md.ath_date?.usd??null,circulatingSupply:md.circulating_supply??null,totalSupply:md.total_supply??null,maxSupply:md.max_supply??null,platforms:Object.keys(data.platforms||{}).filter(p=>p&&p!=="native"),purchaseMarkets}}catch{return null}}
export async function fetchCoinDetails(coinId:string,apiKey?:string){if(apiKey)return coinDetailsRaw(coinId,apiKey);return unstable_cache(()=>coinDetailsRaw(coinId),[`cg-details-${coinId}`],{revalidate:1800,tags:[`coin-${coinId}`,"coin-details"]})()}
export interface CoinSearchResult{id:string;symbol:string;name:string;marketCapRank:number|null;thumb:string|null}export async function searchCoins(query:string,apiKey?:string,limit=8):Promise<CoinSearchResult[]>{if(!query.trim())return[];try{const params=new URLSearchParams({query:query.trim()}),r=await fetchWithRetry(`${SEARCH_URL}?${params}`,apiKey),data=await r.json();return(data.coins||[]).slice(0,limit).map((c:any)=>({id:c.id,symbol:(c.symbol||"").toUpperCase(),name:c.name,marketCapRank:c.market_cap_rank,thumb:c.thumb}))}catch{return[]}}
