import {unstable_cache} from "next/cache";
export type NftCollection={id:string;name:string;slug:string|null;image:string|null;floor:number|null;volume24h:number|null;volume7d:number|null;sales24h:number|null;owners:number|null;tokenCount:number|null;chain:string;marketplaceUrl:string|null};
const API="https://api.opensea.io/api/v2";
function num(v:any){const n=typeof v==="string"?Number(v):v;return typeof n==="number"&&Number.isFinite(n)?n:null}
function first(...values:any[]){return values.find(v=>v!==undefined&&v!==null)}
function mapCollection(c:any):NftCollection{const collection=c.collection||c;const stats=c.stats||c.statistics||{};const total=stats.total||c.total||{};const oneDay=stats.intervals?.find?.((x:any)=>String(x.interval||x.period||"").toLowerCase().includes("day"))||c.one_day||c.oneDay||{};const sevenDay=stats.intervals?.find?.((x:any)=>String(x.interval||x.period||"").toLowerCase().includes("7"))||c.seven_day||c.sevenDay||{};const slug=String(first(collection.slug,c.slug,"")||"")||null;const chainRaw=String(first(collection.chain,c.chain,collection.contracts?.[0]?.chain,"ethereum")||"ethereum");return{id:String(first(slug,collection.id,collection.collection,c.id,collection.name,"unknown")),name:String(first(collection.name,c.name,slug,"Unknown collection")),slug,image:first(collection.image_url,collection.imageUrl,collection.image,c.image_url,c.imageUrl,c.image)||null,floor:num(first(c.floor_price,c.floorPrice,total.floor_price,total.floorPrice,oneDay.floor_price,oneDay.floorPrice)),volume24h:num(first(c.one_day_volume,c.volume_1d,c.volume24h,oneDay.volume,oneDay.total_volume)),volume7d:num(first(c.seven_day_volume,c.volume_7d,c.volume7d,sevenDay.volume,sevenDay.total_volume)),sales24h:num(first(c.one_day_sales,c.sales_1d,c.sales24h,oneDay.sales,oneDay.sales_count)),owners:num(first(c.num_owners,c.owner_count,c.owners,total.num_owners,total.numOwners)),tokenCount:num(first(collection.total_supply,collection.totalSupply,c.total_supply,c.token_count,c.tokenCount)),chain:chainRaw.charAt(0).toUpperCase()+chainRaw.slice(1),marketplaceUrl:slug?`https://opensea.io/collection/${slug}`:null}}
async function request(path:string){const key=process.env.OPENSEA_API_KEY;if(!key)return null;const r=await fetch(`${API}${path}`,{headers:{"x-api-key":key,"accept":"application/json"},signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error(`OpenSea ${r.status}`);return r.json()}
function rows(d:any){if(!d)return[];for(const key of ["collections","results","data","items"]){if(Array.isArray(d[key]))return d[key]}return Array.isArray(d)?d:[]}
async function load(){if(!process.env.OPENSEA_API_KEY)return[];const attempts=["/collections/trending?limit=30&timeframe=ONE_DAY","/collections/top?limit=30","/collections?limit=30&chain=ethereum&order_by=created_date"];
 for(const path of attempts){try{const d=await request(path);const mapped=rows(d).map(mapCollection).filter((c:NftCollection)=>c.slug&&c.name);if(mapped.length)return mapped}catch{}}
 return[]}
export const getNftCollections=unstable_cache(load,["nft-opensea-top"],{revalidate:300,tags:["nft-market"]});
