import Link from "next/link";

export const metadata={title:"Disclaimer | CoinSparkLine",description:"Important information about CoinSparkLine market analytics, SparkScore, cryptoassets, NFTs and portfolio calculations."};

export default function DisclaimerPage(){return <main className="csl-legal-page"><div className="csl-legal-shell">
<Link href="/crypto" className="csl-legal-brand">Coin<span>SparkLine</span></Link>
<p className="csl-legal-eyebrow">LEGAL · DISCLAIMER</p><h1>Market intelligence,<br/>not investment advice.</h1>
<p className="csl-legal-lead">CoinSparkLine is an analytics and information product. Nothing on this website should be treated as financial, investment, legal, tax or other professional advice.</p>
<div className="csl-risk-box"><strong>Cryptoasset and NFT risk</strong><p>Cryptoassets and NFTs are highly volatile and speculative. Their value can fall rapidly and you may lose all of the money you commit. Do not make a financial decision solely because an asset appears on CoinSparkLine or receives a particular score, regime or classification.</p></div>
<section className="csl-legal-grid">
<article><span>01</span><h2>Information only</h2><p>Content, rankings, market observations and analytics are provided for general informational and research purposes. CoinSparkLine does not provide personalised recommendations and does not tell you to buy, sell or hold any asset.</p></article>
<article><span>02</span><h2>SparkScore and classifications</h2><p>SparkScore, market regimes, confidence values, “Moving”, “Building” and other CoinSparkLine labels are proprietary analytical outputs. They describe patterns detected from available data. They are not forecasts, guarantees, trading signals or promises that a market will move in a particular direction.</p></article>
<article><span>03</span><h2>Data and accuracy</h2><p>Market information may originate from third-party providers and can be delayed, incomplete, unavailable or incorrect. Calculations and models can contain errors. CoinSparkLine does not guarantee that prices, NFT data, scores, classifications or other information are accurate, complete or current.</p></article>
<article><span>04</span><h2>Portfolio estimates</h2><p>Portfolio values, cost bases and profit or loss figures are estimates based on information you enter and market data available to CoinSparkLine. They are not official account statements and should not be relied on for tax, accounting or investment decisions.</p></article>
<article><span>05</span><h2>Your decisions</h2><p>You are responsible for your own research and decisions. Consider your circumstances, knowledge, objectives and ability to absorb losses. Where appropriate, obtain advice from an independent qualified professional before acting.</p></article>
<article><span>06</span><h2>Third parties</h2><p>References or links to exchanges, marketplaces, data providers, blockchains, projects or other third parties are provided for information or functionality. Their inclusion does not mean CoinSparkLine endorses, guarantees or controls them.</p></article>
<article><span>07</span><h2>No custody or execution</h2><p>CoinSparkLine is designed as a market analytics product. The current service does not hold your cryptoassets or NFTs, manage investments on your behalf, or execute trades.</p></article>
<article><span>08</span><h2>Availability and liability</h2><p>The service may be changed, interrupted or unavailable. To the fullest extent permitted by applicable law, CoinSparkLine is not responsible for losses arising solely from reliance on informational analytics, third-party data or service interruptions. Nothing here excludes liability that cannot legally be excluded.</p></article>
</section>
<section className="csl-legal-regulatory"><h2>UK users</h2><p>CoinSparkLine should not be interpreted as implying authorisation, approval or endorsement by the Financial Conduct Authority. Cryptoasset communications to UK consumers can be subject to financial-promotion rules. CoinSparkLine is intentionally presented as an analytics and information service rather than a recommendation to invest.</p></section>
<p className="csl-legal-date">Last updated: 25 August 2026</p><nav className="csl-legal-links"><Link href="/crypto">Crypto</Link><Link href="/nft">NFT</Link><Link href="/portfolio">Portfolio</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></nav>
</div></main>}
